CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/Producto_de_Seguros__c.object-meta.xml
<CustomObject>
    <label>Producto de Seguro</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de Seguro</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/Codigo_de_Producto_nectia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Producto_nectia__c</fullName>
    <externalId>true</externalId>
    <label>Codigo Operacional</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/L_nea__c.field-meta.xml
<CustomField>
    <fullName>L_nea__c</fullName>
    <label>Línea</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colectivos</fullName>
            </value>
            <value>
                <fullName>FFMM</fullName>
            </value>
            <value>
                <fullName>Generales</fullName>
            </value>
            <value>
                <fullName>Rentas Vitalicias</fullName>
            </value>
            <value>
                <fullName>Vida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Cliente_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_cliente</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Codigo_Plan_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Plan_Nectia__c</fullName>
    <label>Código Plan</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Esquema_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Esquema_Nectia__c</fullName>
    <label>Esquema</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/L_nea__c.field-meta.xml
<CustomField>
    <fullName>L_nea__c</fullName>
    <formula>TEXT(Producto_de_Seguros_Nectia__r.L_nea__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Línea</label>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Poliza_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Poliza_Nectia__c</fullName>
    <externalId>true</externalId>
    <label>Nº Poliza</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Producto_de_Seguros_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_Seguros_Nectia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto de Seguros</label>
    <referenceTo>Producto_de_Seguros__c</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_del_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Ramo_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Ramo_Nectia__c</fullName>
    <label>Ramo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/CONS_Copia_PolizaTest.cls
@isTest
public class CONS_Copia_PolizaTest {
    static testMethod void test() {
        String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.Codigo_de_Producto_nectia__c = '1111';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Ramo_Nectia__c='05';
        pc.Codigo_Plan_Nectia__c='360';
        pc.Poliza_Nectia__c='12132413';
        pc.Esquema_Nectia__c='SISRVOWPCNS';
        insert pc;
        Case cas=new Case();
        cas.RecordTypeId=[SELECT Id FROM RecordType where SobjectType='case' and Name ='Casos Seguros'].id;
        cas.Accountid=acc.id;
        cas.Status='Nuevo';
        cas.Type='consulta';
        cas.Subtipo__c='Siniestros';
        cas.Clasificaci_n_de_Consulta__c = 'Estado';
        cas.Priority='alta';
        cas.Origin='web';
        cas.Description='problemas de clave de acceso';
        cas.Subject='reclamo';
        cas.SlaStartDate=System.now(); 
        cas.Producto_del_Cliente_Nectia__c=pc.id;
        cas.N_mandato__c='123';
        cas.V_a_de_Pago__c='1';
        cas.Tipo_de_cuenta__c='1';
        
        cas.Rut__c='15555555-6';
        insert cas;
        Attachment adjuntoDoc = new Attachment();
        adjuntoDoc.Name = 'Unit Test Attachment';
        adjuntoDoc.Body = Blob.valueOf('Unit Test Attachment Body');
        adjuntoDoc.ParentId = cas.Id;
        insert adjuntoDoc;
        
        ApexPages.StandardController  astc=new ApexPages.StandardController(pc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Copia_Poliza'));
        System.currentPageReference().getParameters().put('id',pc.Id);
        CONS_Copia_Poliza cp=new CONS_Copia_Poliza(astc);
        //cp.siguiente();
        cp.volver();
        cp.enviar();
        cp.continuar();
        //cp.continuarcaso();
        cp.email=null;
        //cp.siguiente();
         
    }
     static testMethod void test1() {
        String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.Codigo_de_Producto_nectia__c = '1111';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Ramo_Nectia__c='05';
        pc.Codigo_Plan_Nectia__c='360';
        pc.Poliza_Nectia__c='12132413';
        pc.Esquema_Nectia__c='CLONINSUDB';
        insert pc;
        Case cas=new Case();
        cas.RecordTypeId=[SELECT Id FROM RecordType where SobjectType='case' and Name ='Casos Seguros'].id;
        cas.Accountid=acc.id;
        cas.Status='Nuevo';
        cas.Type='consulta';
        cas.Subtipo__c='Siniestros';
        cas.Clasificaci_n_de_Consulta__c = 'Estado';
        cas.Priority='alta';
        cas.Origin='web';
        cas.Description='problemas de clave de acceso';
        cas.Subject='reclamo';
        cas.SlaStartDate=System.now(); 
        cas.Producto_del_Cliente_Nectia__c=pc.id;
        cas.N_mandato__c='123';
        cas.V_a_de_Pago__c='1';
        cas.Tipo_de_cuenta__c='1';
        
        cas.Rut__c='15555555-6';
        insert cas;
        Attachment adjuntoDoc = new Attachment();
        adjuntoDoc.Name = 'Unit Test Attachment';
        adjuntoDoc.Body = Blob.valueOf('Unit Test Attachment Body');
        adjuntoDoc.ParentId = cas.Id;
        insert adjuntoDoc;
        
        ApexPages.StandardController  astc=new ApexPages.StandardController(pc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Copia_Poliza'));
        System.currentPageReference().getParameters().put('id',pc.Id);
        CONS_Copia_Poliza cp=new CONS_Copia_Poliza(astc);
        //cp.siguiente();
        cp.volver();
        cp.enviar();
        cp.continuar();
        //cp.continuarcaso();
        
    }
      static testMethod void test2() {
        String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.Codigo_de_Producto_nectia__c = '1111';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Ramo_Nectia__c='01';
        pc.Codigo_Plan_Nectia__c='360';
        pc.Poliza_Nectia__c='12132413';
        insert pc;
        Case cas=new Case();
        cas.RecordTypeId=[SELECT Id FROM RecordType where SobjectType='case' and Name ='Casos Seguros'].id;
        cas.Accountid=acc.id;
        cas.Status='Nuevo';
        cas.Type='consulta';
        cas.Subtipo__c='Siniestros';
        cas.Clasificaci_n_de_Consulta__c = 'Estado';
        cas.Priority='alta';
        cas.Origin='web';
        cas.Description='problemas de clave de acceso';
        cas.Subject='reclamo';
        cas.SlaStartDate=System.now(); 
        cas.Producto_del_Cliente_Nectia__c=pc.id;
        cas.N_mandato__c='123';
        cas.V_a_de_Pago__c='1';
        cas.Tipo_de_cuenta__c='1';
        
        cas.Rut__c='15555555-6';
        insert cas;
        Attachment adjuntoDoc = new Attachment();
        adjuntoDoc.Name = 'Unit Test Attachment';
        adjuntoDoc.Body = Blob.valueOf('Unit Test Attachment Body');
        adjuntoDoc.ParentId = cas.Id;
        insert adjuntoDoc;
        
        ApexPages.StandardController  astc=new ApexPages.StandardController(pc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Copia_Poliza'));
        System.currentPageReference().getParameters().put('id',pc.Id);
        CONS_Copia_Poliza cp=new CONS_Copia_Poliza(astc);
        cp.siguiente();
        cp.volver();
        cp.enviar();
        cp.continuar();
        cp.continuarcaso();
        cp.orquestaMetodos();
        
    }
      static testMethod void test3() {
        String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.L_nea__c='Rentas Vitalicias';
        pds.Codigo_de_Producto_nectia__c = '1111';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Ramo_Nectia__c='05';
        pc.Codigo_Plan_Nectia__c='360';
        pc.Poliza_Nectia__c='12132413';
        pc.Esquema_Nectia__c='CLONINSUDB';
        insert pc;
        Case cas=new Case();
        cas.RecordTypeId=[SELECT Id FROM RecordType where SobjectType='case' and Name ='Casos Seguros'].id;
        cas.Accountid=acc.id;
        cas.Status='Nuevo';
        cas.Type='consulta';
        cas.Subtipo__c='Siniestros';
        cas.Clasificaci_n_de_Consulta__c = 'Estado';
        cas.Priority='alta';
        cas.Origin='web';
        cas.Description='problemas de clave de acceso';
        cas.Subject='reclamo';
        cas.SlaStartDate=System.now(); 
        cas.Producto_del_Cliente_Nectia__c=pc.id;
        cas.N_mandato__c='123';
        cas.V_a_de_Pago__c='1';
        cas.Tipo_de_cuenta__c='1';
        
        cas.Rut__c='15555555-6';
        insert cas;
        Attachment adjuntoDoc = new Attachment();
        adjuntoDoc.Name = 'Unit Test Attachment';
        adjuntoDoc.Body = Blob.valueOf('Unit Test Attachment Body');
        adjuntoDoc.ParentId = cas.Id;
        insert adjuntoDoc;
        
        ApexPages.StandardController  astc=new ApexPages.StandardController(pc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Copia_Poliza'));
        System.currentPageReference().getParameters().put('id',pc.Id);
        CONS_Copia_Poliza cp=new CONS_Copia_Poliza(astc);
        //cp.siguiente();
        cp.volver();
        cp.enviar();
        cp.continuar();
        cp.verdocumento();
        //cp.continuarcaso();
        
    }
    static testMethod void test34() {
        String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.Codigo_de_Producto_nectia__c = '1111';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Ramo_Nectia__c='05';
        pc.Codigo_Plan_Nectia__c='360';
        pc.Poliza_Nectia__c='12132413';
        pc.Esquema_Nectia__c='INSUDB';
        insert pc;
        Case cas=new Case();
        cas.RecordTypeId=[SELECT Id FROM RecordType where SobjectType='case' and Name ='Casos Seguros'].id;
        cas.Accountid=acc.id;
        cas.Status='Nuevo';
        cas.Type='consulta';
        cas.Subtipo__c='Siniestros';
        cas.Clasificaci_n_de_Consulta__c = 'Estado';
        cas.Priority='alta';
        cas.Origin='web';
        cas.Description='problemas de clave de acceso';
        cas.Subject='reclamo';
        cas.SlaStartDate=System.now(); 
        cas.Producto_del_Cliente_Nectia__c=pc.id;
        cas.N_mandato__c='123';
        cas.V_a_de_Pago__c='1';
        cas.Tipo_de_cuenta__c='1';
        
        cas.Rut__c='15555555-6';
        insert cas;
        Attachment adjuntoDoc = new Attachment();
        adjuntoDoc.Name = 'Unit Test Attachment';
        adjuntoDoc.Body = Blob.valueOf('Unit Test Attachment Body');
        adjuntoDoc.ParentId = cas.Id;
        insert adjuntoDoc;
        
        ApexPages.StandardController  astc=new ApexPages.StandardController(pc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Copia_Poliza'));
        System.currentPageReference().getParameters().put('id',pc.Id);
        CONS_Copia_Poliza cp=new CONS_Copia_Poliza(astc);
        //cp.siguiente();
        cp.volver();
        cp.enviar();
        cp.continuar();
        //cp.continuarcaso();
        cp.email=null;
        //cp.siguiente();
         
    }
        static testMethod void test4() {
         CONS_Respuestacopiapoliza_JSON ev = new CONS_Respuestacopiapoliza_JSON();
        string Json ='{"codigoError":"1", "mensajeError":"testerror", "certificado":{ "archivo":"test", "nombreArchivo":"test"}}';   
          ev = CONS_Respuestacopiapoliza_JSON.parse(Json);
              CONS_Respuestacopiapolizavida_JSON ev1 = new CONS_Respuestacopiapolizavida_JSON();
        string Json1 ='{"codigoError":"1", "mensajeError":"testerror", "certificado":{ "archivo":"test", "nombreArchivo":"test"}}';   
          ev1 = CONS_Respuestacopiapolizavida_JSON.parse(Json);
              CONS_RespuestaCopiaPolizaRV_JSON ev2 = new CONS_RespuestaCopiaPolizaRV_JSON();
        string Json2 ='{"codigoError":"OK", "mensajeError":"testerror", "certificado":{ "archivo":"test", "nombreArchivo":"test"}}';   
          ev2 = CONS_RespuestaCopiaPolizaRV_JSON.parse(Json);
        string Json3 ='{"codigoError":"OK", "mensajeError":"testerror", "certificado":{ "archivo":"test", "nombreArchivo":"test"}}'; 
             CONS_RespuestaCopiaPolizaRV_JSON ev23 = new CONS_RespuestaCopiaPolizaRV_JSON();
          ev23 = CONS_RespuestaCopiaPolizaRV_JSON.parse(Json);
            string Json4 ='{"codigoError":"0", "mensajeError":"testerror", "certificado":{ "archivo":"test", "nombreArchivo":"test"}}';  
      
       
    }
}