CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/Producto_de_Seguros__c.object-meta.xml
<CustomObject>
    <label>Producto de Seguro</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de Seguro</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/Codigo_de_Producto_nectia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Producto_nectia__c</fullName>
    <externalId>true</externalId>
    <label>Codigo Operacional</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Cliente_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_cliente</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Codigo_Plan_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Plan_Nectia__c</fullName>
    <label>Código Plan</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Esquema_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Esquema_Nectia__c</fullName>
    <label>Esquema</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Numero_Certificado_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Numero_Certificado_Nectia__c</fullName>
    <label>Número Certificado</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Poliza_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Poliza_Nectia__c</fullName>
    <externalId>true</externalId>
    <label>Nº Poliza</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Producto_de_Seguros_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_Seguros_Nectia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto de Seguros</label>
    <referenceTo>Producto_de_Seguros__c</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_del_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Ramo_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Ramo_Nectia__c</fullName>
    <label>Ramo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Tipo_Registro_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Registro_Nectia__c</fullName>
    <label>Tipo Registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/CONS_Siniestros_PdC_Controller_test.cls
@isTest
private class CONS_Siniestros_PdC_Controller_test {

	/*@isTest static void test_method_one() {

		Id rtcp = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();

		Account cuenta = new Account();
		cuenta.FirstName = 'cuenta';
		cuenta.LastName = 'cuenta';
		cuenta.RUT__c = '14381623-0';
		cuenta.RecordTypeId = rtcp;
		insert cuenta;

		Producto_de_Seguros__c PdS = new Producto_de_Seguros__c();
		PdS.Name = 'prod seguro';
		PdS.Codigo_de_Producto_nectia__c = '1000';
		insert PdS;

		Producto_del_Cliente__c PdC = new Producto_del_Cliente__c();
		PdC.Name = 'prod cliente';
		PdC.Producto_de_Seguros_Nectia__c = PdS.Id;
		PdC.Cliente_Nectia__c = cuenta.Id;
		PdC.Id__c = '1234514381623-0';
		PdC.Poliza_Nectia__c = '12345';
		PdC.Esquema_Nectia__c = 'INSUDB';
		PdC.Tipo_Registro_Nectia__c = '2';
		PdC.Ramo_Nectia__c = '1';
		PdC.Codigo_Plan_Nectia__c = '650';
		PdC.Numero_Certificado_Nectia__c = '0';
		insert PdC;

		ApexPages.StandardController siniestrosPdC = new ApexPages.StandardController(PdC);
		Test.setCurrentPageReference(new PageReference('Page.CONS_Siniestros_Producto_Cliente'));
		System.currentPageReference().getParameters().put('id',Pdc.Id);
		CONS_Siniestros_PdC_Controller pdcController = new CONS_Siniestros_PdC_Controller(siniestrosPdC);
	}*/

	@isTest static void test_method_two() {

		Id rtcp = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();

		Account cuenta = new Account();
		cuenta.FirstName = 'cuenta';
		cuenta.LastName = 'cuenta';
		cuenta.RUT__c = '14381623-0';
		cuenta.RecordTypeId = rtcp;
		insert cuenta;

		Producto_de_Seguros__c PdS = new Producto_de_Seguros__c();
		PdS.Name = 'prod seguro';
		PdS.Codigo_de_Producto_nectia__c = '1000';
		insert PdS;

		Producto_del_Cliente__c PdC = new Producto_del_Cliente__c();
		PdC.Name = 'prod cliente';
		PdC.Producto_de_Seguros_Nectia__c = PdS.Id;
		PdC.Cliente_Nectia__c = cuenta.Id;
		PdC.Id__c = '1234514381623-0';
		PdC.Poliza_Nectia__c = '12345';
		PdC.Esquema_Nectia__c = 'CLONINSUDB';
		PdC.Tipo_Registro_Nectia__c = '2';
		PdC.Ramo_Nectia__c = '9';
		PdC.Codigo_Plan_Nectia__c = '29';
		PdC.Numero_Certificado_Nectia__c = '0';
		insert PdC;

		ApexPages.StandardController siniestrosPdC = new ApexPages.StandardController(PdC);
		Test.setCurrentPageReference(new PageReference('Page.CONS_Siniestros_Producto_Cliente'));
		System.currentPageReference().getParameters().put('id',Pdc.Id);
		CONS_Siniestros_PdC_Controller pdcController = new CONS_Siniestros_PdC_Controller(siniestrosPdC);
pdcController.listar_vida_o_life();
	}
}