CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/Producto_de_Seguros__c.object-meta.xml
<CustomObject>
    <label>Producto de Seguro</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de Seguro</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/Codigo_de_Producto_nectia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Producto_nectia__c</fullName>
    <externalId>true</externalId>
    <label>Codigo Operacional</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/Familia__c.field-meta.xml
<CustomField>
    <fullName>Familia__c</fullName>
    <label>Familia</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AFP</fullName>
            </value>
            <value>
                <fullName>APV</fullName>
            </value>
            <value>
                <fullName>Fondos Mutuos</fullName>
            </value>
            <value>
                <fullName>INVALIDEZ</fullName>
                <label>Invalidez</label>
            </value>
            <value>
                <fullName>Inversión GOLD</fullName>
            </value>
            <value>
                <fullName>Renta Privada</fullName>
            </value>
            <value>
                <fullName>Renta Privada Sobrevivencia</fullName>
            </value>
            <value>
                <fullName>Renta Privada Vejez</fullName>
            </value>
            <value>
                <fullName>Renta Vitalicia Invalidez</fullName>
            </value>
            <value>
                <fullName>Renta Vitalicia Sobrevivencia</fullName>
            </value>
            <value>
                <fullName>Renta Vitalicia Vejez</fullName>
            </value>
            <value>
                <fullName>Renta Vitalicia Vejez Anticipada</fullName>
            </value>
            <value>
                <fullName>Responsabilidad Civil</fullName>
            </value>
            <value>
                <fullName>Seguro Accidentes</fullName>
            </value>
            <value>
                <fullName>Seguro con Ahorro</fullName>
            </value>
            <value>
                <fullName>Seguro Desgravamen</fullName>
            </value>
            <value>
                <fullName>Seguro Dotal con Ahorro</fullName>
            </value>
            <value>
                <fullName>Seguro Educacional</fullName>
            </value>
            <value>
                <fullName>Seguro Fidelidad</fullName>
            </value>
            <value>
                <fullName>Seguro Flexible con Ahorro</fullName>
            </value>
            <value>
                <fullName>Seguro Hogar</fullName>
            </value>
            <value>
                <fullName>Seguro Incendio</fullName>
            </value>
            <value>
                <fullName>Seguro Incendio Comercial</fullName>
            </value>
            <value>
                <fullName>Seguro Incendio Condominios</fullName>
            </value>
            <value>
                <fullName>Seguro L. Comerciales</fullName>
            </value>
            <value>
                <fullName>Seguro Maquinaria</fullName>
            </value>
            <value>
                <fullName>Seguro Mascotas</fullName>
            </value>
            <value>
                <fullName>Seguro Patrimonial</fullName>
            </value>
            <value>
                <fullName>Seguro Salud</fullName>
            </value>
            <value>
                <fullName>Seguros Colectivos Desgravamen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/L_nea__c.field-meta.xml
<CustomField>
    <fullName>L_nea__c</fullName>
    <label>Línea</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colectivos</fullName>
            </value>
            <value>
                <fullName>FFMM</fullName>
            </value>
            <value>
                <fullName>Generales</fullName>
            </value>
            <value>
                <fullName>Rentas Vitalicias</fullName>
            </value>
            <value>
                <fullName>Vida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Cliente_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_cliente</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Esquema_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Esquema_Nectia__c</fullName>
    <label>Esquema</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/L_nea__c.field-meta.xml
<CustomField>
    <fullName>L_nea__c</fullName>
    <formula>TEXT(Producto_de_Seguros_Nectia__r.L_nea__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Línea</label>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Producto_de_Seguros_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_Seguros_Nectia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto de Seguros</label>
    <referenceTo>Producto_de_Seguros__c</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_del_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/CONS_VisualizarMulticonsultaproductoTest.cls
@isTest
public class CONS_VisualizarMulticonsultaproductoTest {
	static testMethod void TestControlador_1() {
     	String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.Codigo_de_Producto_nectia__c = '1111';
        pds.L_nea__c = 'Vida';
        pds.Familia__c = 'APV';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Esquema_Nectia__c = 'INSUDB';
        insert pc;
        ApexPages.StandardController  astc=new ApexPages.StandardController(pc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Visualizar_MulticonsultaProducto'));
        System.currentPageReference().getParameters().put('id', pc.Id);
        CONS_Visualizar_Multiconsultaproducto sc=new CONS_Visualizar_Multiconsultaproducto(astc);  
        sc.continuar();
    }
    static testMethod void TestControlador_2() {
     	String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.Codigo_de_Producto_nectia__c = '1111';
        pds.L_nea__c = 'Vida';
        pds.Familia__c = 'APV';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Esquema_Nectia__c = 'CLONINSUDB';
        insert pc;
        ApexPages.StandardController  astc=new ApexPages.StandardController(pc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Visualizar_MulticonsultaProducto'));
        System.currentPageReference().getParameters().put('id', pc.Id);
        CONS_Visualizar_Multiconsultaproducto sc=new CONS_Visualizar_Multiconsultaproducto(astc);  
        sc.continuar();
    }
    static testMethod void TestControlador_3() {
     	String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.Codigo_de_Producto_nectia__c = '1111';
        pds.L_nea__c = 'Vida';
        pds.Familia__c = 'APV';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Esquema_Nectia__c = 'VTCNLIFE';
        insert pc;
        ApexPages.StandardController  astc=new ApexPages.StandardController(pc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Visualizar_MulticonsultaProducto'));
        System.currentPageReference().getParameters().put('id', pc.Id);
        CONS_Visualizar_Multiconsultaproducto sc=new CONS_Visualizar_Multiconsultaproducto(astc);  
        sc.continuar();
    }
    
      static testMethod void TestControlador_4() {
     	String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.Codigo_de_Producto_nectia__c = '1111';
        pds.L_nea__c = 'Vida';
        pds.Familia__c = 'APV';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Esquema_Nectia__c = 'VTCNLIFE';
        insert pc;
        ApexPages.StandardController  astc=new ApexPages.StandardController(acc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Visualizar_Multiconsulta'));
       // System.currentPageReference().getParameters().put('id', pc.Id);
        CONS_Visualizar_Multiconsulta sc=new CONS_Visualizar_Multiconsulta(astc);  
       
    }
      static testMethod void TestControlador_5() {
     	String recordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Cliente Persona Seguros').getRecordTypeId();
        account  acc=new account();
        acc.FirstName='test';
        acc.LastName = 'test';
        acc.RecordTypeId=recordTypeId;
        acc.rut__c='6676081-2';
        acc.PersonEmail = 'test@test.cl';
        insert acc;
        
        Producto_de_Seguros__c pds=new Producto_de_Seguros__c();
        pds.Name='Renta Vitalicia';
        pds.Codigo_de_Producto_nectia__c = '1111';
        pds.L_nea__c = 'Vida';
        pds.Familia__c = 'APV';
        insert pds;
        Producto_del_Cliente__c pc=new Producto_del_Cliente__c();
        pc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Seguros'].id;
        pc.Cliente_Nectia__c=acc.id;
        pc.Producto_de_Seguros_Nectia__c=pds.id;
        pc.Name='Renta Vitalicia';
        pc.Id__c='12345678901';
        pc.Esquema_Nectia__c = 'VTCNLIFE';
        insert pc;
        ApexPages.StandardController  astc=new ApexPages.StandardController(pc);
        Test.setCurrentPageReference(new PageReference('Page.CONS_Visualizar_Multiservicio'));
        System.currentPageReference().getParameters().put('id', pc.Id);
        CONS_Visualizar_Multiservicio sc=new CONS_Visualizar_Multiservicio(astc);  
       
    }
    
}