CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org_B2B__c/Consorcio_Org_B2B__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Indica que perfiles pueden activas componentes en proyecto banca personas</description>
    <label>Consorcio Org B2B</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org_B2B__c/fields/Carga_Masiva_de_Prospectos__c.field-meta.xml
<CustomField>
    <fullName>Carga_Masiva_de_Prospectos__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Valida que el perfil active el proceso de asignación y validaciones en la carga masiva de prospectos y clientes asociados a las campañas y/o envíos masivos</description>
    <label>Carga Masiva de Prospectos</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/CampaignTriggerHandlerB2B.cls
/**
 * @description       : Handler Campaign B2B
 * @author            : mbeltran@everis.com
 * @group             : 
 * @last modified on  : 09-08-2020
 * @last modified by  : mbeltran@everis.com
 * Modifications Log 
 * Ver   Date         Author                Modification
 * 1.0   08-26-2020   mbeltran@everis.com   Initial Version
**/
public without sharing class CampaignTriggerHandlerB2B {
    private static Consorcio_Org_B2B__c orgB2B = ProcessControlHelper.shouldRunProcessB2B();
   

    /**
    * @description 
    * @author mbeltran@everis.com | 09-08-2020 
    * @param List<Campaign> newCampaignList 
    * @param Map<Id Campaign> oldCampaignMap 
    **/
    public static void onBeforeUpdate(List<Campaign> newCampaignList, Map<Id, Campaign> oldCampaignMap){
      if(orgB2B.Carga_Masiva_de_Prospectos__c){
        CampaignTriggerHelperB2B.CloseLeadsinCampaignMemberwheCampaignClose(newCampaignList, oldCampaignMap);
      }
    }
}