CNSDEVCOLECT/force-app/main/default/objects/DocumentosAlfresco__c/DocumentosAlfresco__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista de documentos que se cargarán en Alfresco, con un identificador por tipo de documentos. Ejemplo: Portabilida u Oportunidad.</description>
    <label>DocumentosAlfresco</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/DocumentosAlfresco__c/fields/Escritura__c.field-meta.xml
<CustomField>
    <fullName>Escritura__c</fullName>
    <label>Escritura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/DocumentosAlfresco__c/fields/Lectura__c.field-meta.xml
<CustomField>
    <fullName>Lectura__c</fullName>
    <label>Lectura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/DocumentosAlfresco__c/fields/NombreDocumento__c.field-meta.xml
<CustomField>
    <fullName>NombreDocumento__c</fullName>
    <label>NombreDocumento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/DocumentosAlfresco__c/fields/OrdenListDoc__c.field-meta.xml
<CustomField>
    <fullName>OrdenListDoc__c</fullName>
    <label>OrdenListDoc</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/DocumentosAlfresco__c/fields/OrigenDocumento__c.field-meta.xml
<CustomField>
    <fullName>OrigenDocumento__c</fullName>
    <label>OrigenDocumento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/Object_Related_Document__c.object-meta.xml
<CustomObject>
    <label>Object Related Document</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Docu Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Related Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que valida si un documento ya fue aprobado y bloquea la picklist</description>
    <label>Documento Aprobado</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Caso_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Caso_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso Relacionado</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Object Related Document</relationshipLabel>
    <relationshipName>Object_Related_Document</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Check_Documento__c.field-meta.xml
<CustomField>
    <fullName>Check_Documento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Documento</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Detalle_Documento__c.field-meta.xml
<CustomField>
    <fullName>Detalle_Documento__c</fullName>
    <description>Guarda el detalle del documento adicional solicitado.</description>
    <label>Detalle Documento</label>
    <type>TextArea</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Estado_Documento__c.field-meta.xml
<CustomField>
    <fullName>Estado_Documento__c</fullName>
    <description>Campo para almacenar el estado del documento en la Oportunidad</description>
    <label>Estado del Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ingresado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>No aplica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Concatena el Id del objeto relacionado y el nombre del documento</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Fecha_Carga_Alfresco__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Carga_Alfresco__c</fullName>
    <label>Fecha Carga Alfresco</label>
    <type>Date</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Id_Alfresco__c.field-meta.xml
<CustomField>
    <fullName>Id_Alfresco__c</fullName>
    <description>Id documento cargado en Alfresco</description>
    <externalId>true</externalId>
    <label>Id Alfresco</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Id_Doc_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Id_Doc_Attachment__c</fullName>
    <label>Id Doc Attachment</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Motivo_Rechazo__c.field-meta.xml
<CustomField>
    <fullName>Motivo_Rechazo__c</fullName>
    <description>Campo para almacenar el motivo por el cual se rechazo un documento en la oportunidad</description>
    <label>Motivo de Rechazo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documento No Corresponde</fullName>
            </value>
            <value>
                <fullName>Documento Ilegible</fullName>
            </value>
            <value>
                <fullName>Documento Incompleto</fullName>
            </value>
            <value>
                <fullName>Expirado</fullName>
                <isActive>false</isActive>
                <label>Expirado</label>
            </value>
            <value>
                <fullName>No Legible</fullName>
                <isActive>false</isActive>
                <label>No Legible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Orden_Documento__c.field-meta.xml
<CustomField>
    <fullName>Orden_Documento__c</fullName>
    <label>Orden Documento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Object_Related_Document__c/fields/Tipo_Documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Documento__c</fullName>
    <description>Campo para almacenar los tipos de documentos que se solicitan en recopilación para hipotecario.</description>
    <label>Tipo de Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/ObjectRelatedDocumentHelper.cls
/*********************************************************************************************************
@Author       cagonzle@everis.com
@name         ObjectRelatedDocumentHelper
@CreateDate   30/09/2020
@Description  Implementation of Alfresco Integration  
***********************************************************************************************************
History of changes: 
-----------------------------------------------------------------------------------------------------------
Date                               Developer                         Comments   
-----------------------------------------------------------------------------------------------------------
30/09/2020                    cagonzle@everis.com          			Implementacion PF
**********************************************************************************************************/
public with sharing class ObjectRelatedDocumentHelper {

    private static final String ORIGEN_PF = 'Portabilidad Financiera Entrada';//'Portabilidad';
   
    public static Map<String, Object_Related_Document__c> objRelDocMap {get; set;}
    public static List<DocumentosAlfresco__c> docAlfresco  {get; set;}
    public static Set<String> autoLoadDocs  {get; set;}
    
    public static List<DocumentosAlfresco__c> loadSettings(String origen){
		if(docAlfresco == null){
			docAlfresco = [select NombreDocumento__c, Name, Lectura__c, Escritura__c from DocumentosAlfresco__c where OrigenDocumento__c =: origen order by OrdenListDoc__c asc ];
            autoLoadDocs = new Set<String>();
            for(DocumentosAlfresco__c da : docAlfresco){
                if(da.Escritura__c == 'INTEGRACION'){
                    autoLoadDocs.add(da.NombreDocumento__c);
                }
            }
		}
        return docAlfresco;
    }

    public static Object_Related_Document__c getRecord(String sKey){
        if(objRelDocMap.containsKey(sKey.toLowerCase())){
            return objRelDocMap.get(sKey.toLowerCase());
        }else{
        	Object_Related_Document__c newDocLog = new Object_Related_Document__c();
            objRelDocMap.put(sKey.toLowerCase(),newDocLog);
            return newDocLog;
        }
    }

    public static void matchRecords(Id idObj, String objField, String origen){

		loadSettings(origen);
        if(objRelDocMap == null){
            objRelDocMap = new Map<String,Object_Related_Document__c>();
            
            String query = 'SELECT Tipo_Documento__c, Aprobado__c, Check_Documento__c, Detalle_Documento__c, Estado_Documento__c, Id_Alfresco__c, Motivo_Rechazo__c, ' +
                'Orden_Documento__c, Fecha_Carga_Alfresco__c, ' + objField + ' ' +
                'FROM Object_Related_Document__c WHERE '+objField+' = \''+idObj+'\'';
            String sKey = '';

            List<Object_Related_Document__c> docuObj = new List<Object_Related_Document__c>();
            try{
                docuObj = database.query(query);
            }catch(Exception e){
                docuObj = new List<Object_Related_Document__c>();
            }

            for(Object_Related_Document__c obj : docuObj){
                sKey = obj.Tipo_Documento__c;
                objRelDocMap.put(sKey.toLowerCase(), obj);
            }
            
            List<Object_Related_Document__c> lstDocsLog = new List<Object_Related_Document__c>();
            Object_Related_Document__c objLog;     
            for (DocumentosAlfresco__c docum : docAlfresco){
                objLog = getRecord(docum.NombreDocumento__c);
                if(objLog.Id == null){
                	objLog.Caso_Relacionado__c = idObj;
                    objLog.Tipo_Documento__c = docum.NombreDocumento__c;
                    objLog.External_Id__c = idObj + '-' + docum.NombreDocumento__c;
                    lstDocsLog.add(objLog);
                }
            }
            
            if (!lstDocsLog.isEmpty()){
                upsert lstDocsLog; 
            }
        }
    }

    public static List<ResponseDTOAlfresco> createLogDocPF(List<Attachment> lstAtt, String sourceip){
        
        ObjectRelatedDocumentHelper.loadSettings(ORIGEN_PF);
        Set<Id> lstIds = new Set<Id>();        
        List<ResponseDTOAlfresco> lstDtoAlf = new List<ResponseDTOAlfresco>();
       
        for(Attachment att : lstAtt){
            lstIds.add(att.ParentId);
        } 
         
        if(lstIds.size() > 0){
            Map<Id, Case> mapCaseByAtt = new Map<Id, Case>();
            for(Case caso : [SELECT AccountId, Account.Rut__c FROM Case WHERE Id IN: lstIds]){
                mapCaseByAtt.put(caso.Id, caso);
            }	            
            List<Object_Related_Document__c> lstDocsLog = new List<Object_Related_Document__c>();
            Set<String> attIdSet = new Set<String>();
            
            for(Attachment att : lstAtt){
                FileUploadServiceController.sourceIp = sourceip;
                ResponseDTOAlfresco response = FileUploadServiceController.invokeUploadAlfresco(att, new List<Case>{mapCaseByAtt.get(att.ParentId)});		
                lstDtoAlf.add(response);

                Object_Related_Document__c ord = createDocsOftrigger(response, att.ParentId, 'Caso_Relacionado__c', att);
                if(ord != null){ if(ord.External_Id__c != null){ lstDocsLog.add(ord); } }                 
            }

            if(lstDocsLog.size() > 0 ){
                Upsert lstDocsLog External_Id__c;
            }           
        }
        return lstDtoAlf;
    }
    
    public static Object_Related_Document__c createDocsOftrigger(ResponseDTOAlfresco response, ID idObj, String apiObj, Attachment a){
        Date myDate = Date.today();
        Object_Related_Document__c objLog = new Object_Related_Document__c();
        
        if(response.salidaAlfresco!=null){            
            if (response.salidaAlfresco.idAlfresco!='' && response.salidaAlfresco.idAlfresco!=null) {
                objLog.put(apiObj, idObj);
                objLog.Tipo_Documento__c = a.Description;
                objLog.External_Id__c = idObj + '-' + a.Description;
                objLog.Estado_Documento__c = 'Ingresado';
                objLog.Id_Alfresco__c = response.salidaAlfresco.idAlfresco;
                objLog.Fecha_Carga_Alfresco__c = myDate;
                objlog.Id_Doc_Attachment__c = a.Id;
            }
        }
        return objLog;
    }
}