CNSDEVCOLECT/force-app/main/default/objects/ProfileApprovBank__c/ProfileApprovBank__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Asignacion de Jefe de Visado y Riesgo</description>
    <label>Ejecutivos Aprobadores Banca</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/ProfileApprovBank__c/fields/Rut__c.field-meta.xml
<CustomField>
    <fullName>Rut__c</fullName>
    <label>Rut</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/AddApprovalController_Test.cls
/**
 * @File Name          : AddApprovalController_Test.cls
 * @Description        : 
 * @Author             : pcelisbe@everis.com
 * @Group              : 
 * @Last Modified By   : 
 * @Last Modified On   : 
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    11-03-2020   pcelisbe@everis.com     Initial Version
**/
@isTest
public class AddApprovalController_Test {

    @testSetup static void dataload(){
        TestFactorySales.populateOrg();
       	TestFactorySales.createConsorcioOrg();
    }
    
    @isTest private static void save(){
        //User u = [select id,Name,rut__c from User where id =: userInfo.getUserId()];
        User u = [select id,Name,rut__c from User where rut__c ='9267710-9' LIMIT 1];

        sYSTEM.debug(u);
        ProfileApprovBank__c pA = new ProfileApprovBank__c();
        pA.Name='Ejecutivo de Visado';
        pA.Rut__c=u.RUT__c;
     	insert pA;
        Opportunity opp=[SELECT id FROM Opportunity WHERE ownerId=:u.Id];

        System.runAs(u){
        
        Boolean Result =AddApprovalController.save(u.id, opp.id);

        
		System.assert(result);        
            }
    }
}