CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/Oferta__c.object-meta.xml
<CustomObject>
    <description>Objeto creado para contener las ofertas insertadas por Analytics.</description>
    <label>Oferta</label>
    <nameField>
        <label>Oferta Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ofertas</relationshipLabel>
    <relationshipName>Ofertas</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/comentario_oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>comentario_oferta_sales__c</fullName>
    <label>Comentario Oferta</label>
    <type>TextArea</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Descripcion_oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_oferta_sales__c</fullName>
    <description>Campo de texto enriquecido para descripción de la oferta</description>
    <label>Descripcion oferta</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Ejecutivo_sales__c.field-meta.xml
<CustomField>
    <fullName>Ejecutivo_sales__c</fullName>
    <label>Ejecutivo Contacto</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Estado_Oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Estado_Oferta_sales__c</fullName>
    <label>Estado Oferta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gestionado</fullName>
            </value>
            <value>
                <fullName>No Gestionado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Familia_Producto_sales__c.field-meta.xml
<CustomField>
    <fullName>Familia_Producto_sales__c</fullName>
    <label>Familia Producto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUTO</fullName>
            </value>
            <value>
                <fullName>HOGAR</fullName>
            </value>
            <value>
                <fullName>RRVV</fullName>
            </value>
            <value>
                <fullName>VIDA</fullName>
            </value>
            <value>
                <fullName>CUENTA VISTA</fullName>
            </value>
            <value>
                <fullName>PLAN PLUS</fullName>
            </value>
            <value>
                <fullName>CREDITO DE CONSUMO</fullName>
            </value>
            <value>
                <fullName>INVERSIONES</fullName>
            </value>
            <value>
                <fullName>CREDITO HIPOTECARIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Interes_Oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Interes_Oferta_sales__c</fullName>
    <label>Interés Oferta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interesado</fullName>
            </value>
            <value>
                <fullName>No Interesado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Motivo_no_interes_sales__c.field-meta.xml
<CustomField>
    <fullName>Motivo_no_interes_sales__c</fullName>
    <label>Motivo no Interés</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cesante</fullName>
            </value>
            <value>
                <fullName>Mejor Oferta Competencia</fullName>
            </value>
            <value>
                <fullName>No quiere endeudarse</fullName>
            </value>
            <value>
                <fullName>Oferta poco atractiva</fullName>
            </value>
            <value>
                <fullName>Descontento con Consorcio</fullName>
            </value>
            <value>
                <fullName>Situación COVID</fullName>
            </value>
            <value>
                <fullName>Cómodo con su banco</fullName>
            </value>
            <value>
                <fullName>Sin interés en Refinanciar</fullName>
            </value>
            <value>
                <fullName>Características de producto</fullName>
                <isActive>false</isActive>
                <label>Características de producto</label>
            </value>
            <value>
                <fullName>Mala experiencia con CNS</fullName>
                <isActive>false</isActive>
                <label>Mala experiencia con CNS</label>
            </value>
            <value>
                <fullName>Mejor oferta otra compañía</fullName>
                <isActive>false</isActive>
                <label>Mejor oferta otra compañía</label>
            </value>
            <value>
                <fullName>No tiene capacidad económica</fullName>
                <isActive>false</isActive>
                <label>No tiene capacidad económica</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Ofertas</relationshipLabel>
    <relationshipName>Ofertas</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Origen_sales__c.field-meta.xml
<CustomField>
    <fullName>Origen_sales__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Owner_Opp_sales__c.field-meta.xml
<CustomField>
    <fullName>Owner_Opp_sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Propietario de la oportunidad a generar, según Ejecutivo informado por Analytics</description>
    <label>Responsable Oportunidad</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ofertas</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Rut_Cliente_sales__c.field-meta.xml
<CustomField>
    <fullName>Rut_Cliente_sales__c</fullName>
    <label>Rut Cliente</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/telefono_ivr_sales__c.field-meta.xml
<CustomField>
    <fullName>telefono_ivr_sales__c</fullName>
    <description>Campo creado por everis para contener el número de teléfono de la Oferta que luego se traspasará a la Oportunidad.</description>
    <label>Télefono IVR</label>
    <type>Phone</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Vigencia_Oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Vigencia_Oferta_sales__c</fullName>
    <label>Vigencia Oferta</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Vigente_sales__c.field-meta.xml
<CustomField>
    <fullName>Vigente_sales__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/OfferCmpController.cls
/**
 * @File Name          : OfferCmpController.cls
 * @Description        : 
 * @Author             : eayalcor@everis.com
 * @Group              : 
 * @Last Modified By   : eayalcor@everis.com
 * @Last Modified On   : 6/12/2020, 1:48:06 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    6/1/2020   eayalcor@everis.com     Initial Version
**/
public with sharing class OfferCmpController {

    /**
    * @description 
    * @author eayalcor@everis.com | 6/1/2020 
    * @param Id offerId 
    * @return responseData 
    **/
    @AuraEnabled
    public static responseData getInitialData(Id offerId){
        ResponseData data = new ResponseData();

        List<Oferta__c> lstOffer = [SELECT Id,Name,AccountId__c,Ejecutivo_sales__c,Rut_Cliente_sales__c,Vigente_sales__c,
        Familia_Producto_sales__c,Vigencia_Oferta_sales__c,Motivo_no_interes_sales__c,Estado_Oferta_sales__c FROM Oferta__c WHERE Id =: offerId];

        data.reasons = UtilitiesSales.getPicklistData(Oferta__c.Motivo_no_interes_sales__c);

        if(lstOffer!= null || !lstOffer.isEmpty()){
            data.offer = lstOffer[0];
        }else{
            data.offer = null;
        }

        return data;
    }

    /**
    * @description 
    * @author eayalcor@everis.com | 6/1/2020 
    * @param Id offerId 
    * @param String reason 
    * @return string 
    **/
    @AuraEnabled
    public static string rejectOffer(Id offerId,String reason){
        try{
            Oferta__c offer = new Oferta__c();
            offer.Id = offerId;
            offer.Interes_Oferta_sales__c = Constants.OFERTA_NOINTERESADO;
            offer.Estado_Oferta_sales__c = Constants.OFERTA_GESTIONADO;
            offer.Motivo_no_interes_sales__c = reason;
            offer.Vigente_sales__c = false;
            offer.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName =: Constants.OFERTA_SALES_RECORDTYPE_LECTURA AND SobjectType =: Constants.OFERTA LIMIT 1].Id;
            update offer;
    
            return Constants.OK;

        }catch (Exception ex){
            return 'ERROR: Contactar a su Administrador';
        }finally {
            Set<Id> setOffers = new Set<Id>{offerId};
            SalesCallout.futureNotifyAnalyticsOffer(setOffers, Constants.INSERTED);
        }
    }

    /**
    * @description 
    * @author eayalcor@everis.com | 6/1/2020 
    * @param Id offerId 
    * @return string 
    **/
    @AuraEnabled
    public static string generateOpportunity(Id offerId,String obs){
        try{
            List<Oferta__c> lstOffer = [SELECT Id,Name,AccountId__c, telefono_ivr_sales__c, Ejecutivo_sales__c,Rut_Cliente_sales__c,AccountId__r.firstName,Vigente_sales__c,comentario_oferta_sales__c,
            AccountId__r.lastName,Familia_Producto_sales__c,Vigencia_Oferta_sales__c,Motivo_no_interes_sales__c,Estado_Oferta_sales__c,Origen_sales__c,Owner_Opp_sales__c,Descripcion_oferta_sales__c  
            FROM Oferta__c WHERE Id =: offerId];

            String rtByFamily = UtilitiesSales.getRTbyFamilyProduct(lstOffer[0].Familia_Producto_sales__c);
            Integer count =[SELECT COUNT() FROM Opportunity WHERE AccountId=:lstOffer[0].AccountId__c]+1;
            /*
            Creación Opportunity
            */
            Opportunity newOpp = new Opportunity();
            newOpp.StageName = Constants.OPPORTUNITY_STAGE_CONTACTO;
            newOpp.CloseDate = Date.TODAY().addMonths(1);
            newOpp.AccountId = lstOffer[0].AccountId__c;
            newOpp.Name = lstOffer[0].Familia_Producto_sales__c + ' - ' + count +' - '+lstOffer[0].AccountId__r.firstName + ' '+lstOffer[0].AccountId__r.lastName;
            newOpp.origen_de_oportunidad_sales__c = lstOffer[0].Origen_sales__c;
            newOpp.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName =: rtByFamily LIMIT 1].Id;
            newOpp.OwnerId = lstOffer[0].Owner_Opp_sales__c;
            newOpp.comentario_oferta_sales__c = obs;
            newOpp.Flag_Banca_Nueva_Oportunidad_sales__c = true;
            newOpp.Descripcion_Analitycs__c = lstOffer[0].Descripcion_oferta_sales__c;
            newOpp.telefono_oportunidad_sales__c = lstOffer[0].telefono_ivr_sales__c;
            newOpp.flag_creacion_oferta_sales__c = true;
            insert newOpp;

            lstOffer[0].Interes_Oferta_sales__c = Constants.OFERTA_INTERESADO;
            lstOffer[0].Estado_Oferta_sales__c = Constants.OFERTA_GESTIONADO;
            lstOffer[0].OpportunityId__c = newOpp.Id;
            lstOffer[0].Vigente_sales__c = false;
            lstOffer[0].comentario_oferta_sales__c = obs;
            lstOffer[0].RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName =: Constants.OFERTA_SALES_RECORDTYPE_LECTURA AND SobjectType =: Constants.OFERTA LIMIT 1].Id;

            update lstOffer;

            return Constants.OK;


        }catch(Exception ex){
            System.debug('ERROR:' +ex.getStackTraceString() + ' ' + ex.getMessage());
            return 'ERROR: Contactar a su Administrador';
        }finally {
            Set<Id> setOffers = new Set<Id>{offerId};
            SalesCallout.futureNotifyAnalyticsOffer(setOffers, Constants.INSERTED);
        }
    }

    public class ResponseData{
        @AuraEnabled public List<String> reasons;
        @AuraEnabled public Oferta__c offer;
    }

    public class NotifyAnalyticOffer{
        public String message {get;set;}
        public Integer code {get;set;}
        public String action {get;set;}
        public List<Oferta__c> OfertaList;

    }
}