CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/Oferta__c.object-meta.xml
<CustomObject>
    <description>Objeto creado para contener las ofertas insertadas por Analytics.</description>
    <label>Oferta</label>
    <nameField>
        <label>Oferta Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/comentario_oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>comentario_oferta_sales__c</fullName>
    <label>Comentario Oferta</label>
    <type>TextArea</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Descripcion_oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_oferta_sales__c</fullName>
    <description>Campo de texto enriquecido para descripción de la oferta</description>
    <label>Descripcion oferta</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Detalle_sales__c.field-meta.xml
<CustomField>
    <fullName>Detalle_sales__c</fullName>
    <label>Detalle</label>
    <type>TextArea</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Ejecutivo_sales__c.field-meta.xml
<CustomField>
    <fullName>Ejecutivo_sales__c</fullName>
    <label>Ejecutivo Contacto</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Estado_Oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Estado_Oferta_sales__c</fullName>
    <label>Estado Oferta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gestionado</fullName>
            </value>
            <value>
                <fullName>No Gestionado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Familia_Producto_sales__c.field-meta.xml
<CustomField>
    <fullName>Familia_Producto_sales__c</fullName>
    <label>Familia Producto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUTO</fullName>
            </value>
            <value>
                <fullName>HOGAR</fullName>
            </value>
            <value>
                <fullName>RRVV</fullName>
            </value>
            <value>
                <fullName>VIDA</fullName>
            </value>
            <value>
                <fullName>CUENTA VISTA</fullName>
            </value>
            <value>
                <fullName>PLAN PLUS</fullName>
            </value>
            <value>
                <fullName>CREDITO DE CONSUMO</fullName>
            </value>
            <value>
                <fullName>INVERSIONES</fullName>
            </value>
            <value>
                <fullName>CREDITO HIPOTECARIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Interes_Oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Interes_Oferta_sales__c</fullName>
    <label>Interés Oferta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interesado</fullName>
            </value>
            <value>
                <fullName>No Interesado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Motivo_no_interes_sales__c.field-meta.xml
<CustomField>
    <fullName>Motivo_no_interes_sales__c</fullName>
    <label>Motivo no Interés</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cesante</fullName>
            </value>
            <value>
                <fullName>Mejor Oferta Competencia</fullName>
            </value>
            <value>
                <fullName>No quiere endeudarse</fullName>
            </value>
            <value>
                <fullName>Oferta poco atractiva</fullName>
            </value>
            <value>
                <fullName>Descontento con Consorcio</fullName>
            </value>
            <value>
                <fullName>Situación COVID</fullName>
            </value>
            <value>
                <fullName>Cómodo con su banco</fullName>
            </value>
            <value>
                <fullName>Sin interés en Refinanciar</fullName>
            </value>
            <value>
                <fullName>Características de producto</fullName>
                <isActive>false</isActive>
                <label>Características de producto</label>
            </value>
            <value>
                <fullName>Mala experiencia con CNS</fullName>
                <isActive>false</isActive>
                <label>Mala experiencia con CNS</label>
            </value>
            <value>
                <fullName>Mejor oferta otra compañía</fullName>
                <isActive>false</isActive>
                <label>Mejor oferta otra compañía</label>
            </value>
            <value>
                <fullName>No tiene capacidad económica</fullName>
                <isActive>false</isActive>
                <label>No tiene capacidad económica</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Ofertas</relationshipLabel>
    <relationshipName>Ofertas</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Origen_sales__c.field-meta.xml
<CustomField>
    <fullName>Origen_sales__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Rut_Cliente_sales__c.field-meta.xml
<CustomField>
    <fullName>Rut_Cliente_sales__c</fullName>
    <label>Rut Cliente</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/telefono_ivr_sales__c.field-meta.xml
<CustomField>
    <fullName>telefono_ivr_sales__c</fullName>
    <description>Campo creado por everis para contener el número de teléfono de la Oferta que luego se traspasará a la Oportunidad.</description>
    <label>Télefono IVR</label>
    <type>Phone</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Vigencia_Oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Vigencia_Oferta_sales__c</fullName>
    <label>Vigencia Oferta</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Vigente_sales__c.field-meta.xml
<CustomField>
    <fullName>Vigente_sales__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Vigente</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/OfferValidityBatch.cls
/**
 * @File Name          : OfferValidityBatch.cls
 * @Description        : 
 * @Author             : eayalcor@everis.com
 * @Group              : 
 * @Last Modified By   : eayalcor@everis.com
 * @Last Modified On   : 07-29-2020
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    6/12/2020   eayalcor@everis.com     Initial Version
**/
global class OfferValidityBatch implements Database.Batchable<sObject>, Database.AllowsCallouts  {
    global Database.QueryLocator start(Database.BatchableContext BC){

        // collect the batches of records or objects to be passed to execute
        DateTime currentTime = System.now();
        String CT = currentTime.format('yyyy-MM-dd');

        return Database.getQueryLocator('SELECT Id,Name,Ejecutivo_sales__c,Rut_Cliente_sales__c,Vigencia_Oferta_sales__c,Familia_Producto_sales__c,'+
                                        'Descripcion_oferta_sales__c,Detalle_sales__c,Origen_sales__c,Interes_Oferta_sales__c,OpportunityId__c, Motivo_no_interes_sales__c,' +
                                        'comentario_oferta_sales__c, telefono_ivr_sales__c FROM Oferta__c WHERE Vigente_sales__c = true AND Estado_Oferta_sales__c = \''+CONSTANTS.OFERTA_NOGESTIONADO+'\' AND '+
                                        'Vigencia_Oferta_sales__c <'+CT);

    }
     
    global void execute(Database.BatchableContext BC, List<Oferta__c> lstObj){
            List<Oferta__c> lstOffer = new List<Oferta__c>();

            for(Oferta__c offer : lstObj){
                offer.Vigente_sales__c = false;
                offer.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName =: Constants.OFERTA_SALES_RECORDTYPE_LECTURA AND SobjectType =: Constants.OFERTA LIMIT 1].Id;
                offer.OpportunityId__c = offer.OpportunityId__c == null ? null : offer.OpportunityId__c;
                offer.Motivo_no_interes_sales__c = offer.Motivo_no_interes_sales__c == null ? null : offer.Motivo_no_interes_sales__c;  
                offer.comentario_oferta_sales__c = offer.comentario_oferta_sales__c == null ? null : offer.comentario_oferta_sales__c; 
                offer.telefono_ivr_sales__c = offer.telefono_ivr_sales__c == null ? null : offer.telefono_ivr_sales__c; 
                lstOffer.add(offer);
            }

            SalesCallout sc = new SalesCallout(Constants.ANALYTICSLEAD);
            OfferCmpController.NotifyAnalyticOffer obj = new OfferCmpController.NotifyAnalyticOffer();
            obj.code = 200;
            obj.message = null;
            obj.action = Constants.INSERTED;
            obj.OfertaList = lstOffer;

            sc.notifyAnalyticsOffer(obj);

            List<Database.UpsertResult> updateResults = Database.upsert(lstOffer,false);

    }   
     
    global void finish(Database.BatchableContext BC){
        // execute any post-processing operations like sending email
    }
}