CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/Oferta__c.object-meta.xml
<CustomObject>
    <description>Objeto creado para contener las ofertas insertadas por Analytics.</description>
    <label>Oferta</label>
    <nameField>
        <label>Oferta Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ofertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ofertas</relationshipLabel>
    <relationshipName>Ofertas</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Descripcion_oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_oferta_sales__c</fullName>
    <description>Campo de texto enriquecido para descripción de la oferta</description>
    <label>Descripcion oferta</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Detalle_sales__c.field-meta.xml
<CustomField>
    <fullName>Detalle_sales__c</fullName>
    <label>Detalle</label>
    <type>TextArea</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Ejecutivo_sales__c.field-meta.xml
<CustomField>
    <fullName>Ejecutivo_sales__c</fullName>
    <label>Ejecutivo Contacto</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Estado_Oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Estado_Oferta_sales__c</fullName>
    <label>Estado Oferta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gestionado</fullName>
            </value>
            <value>
                <fullName>No Gestionado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Familia_Producto_sales__c.field-meta.xml
<CustomField>
    <fullName>Familia_Producto_sales__c</fullName>
    <label>Familia Producto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AUTO</fullName>
            </value>
            <value>
                <fullName>HOGAR</fullName>
            </value>
            <value>
                <fullName>RRVV</fullName>
            </value>
            <value>
                <fullName>VIDA</fullName>
            </value>
            <value>
                <fullName>CUENTA VISTA</fullName>
            </value>
            <value>
                <fullName>PLAN PLUS</fullName>
            </value>
            <value>
                <fullName>CREDITO DE CONSUMO</fullName>
            </value>
            <value>
                <fullName>INVERSIONES</fullName>
            </value>
            <value>
                <fullName>CREDITO HIPOTECARIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Motivo_no_interes_sales__c.field-meta.xml
<CustomField>
    <fullName>Motivo_no_interes_sales__c</fullName>
    <label>Motivo no Interés</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cesante</fullName>
            </value>
            <value>
                <fullName>Mejor Oferta Competencia</fullName>
            </value>
            <value>
                <fullName>No quiere endeudarse</fullName>
            </value>
            <value>
                <fullName>Oferta poco atractiva</fullName>
            </value>
            <value>
                <fullName>Descontento con Consorcio</fullName>
            </value>
            <value>
                <fullName>Situación COVID</fullName>
            </value>
            <value>
                <fullName>Cómodo con su banco</fullName>
            </value>
            <value>
                <fullName>Sin interés en Refinanciar</fullName>
            </value>
            <value>
                <fullName>Características de producto</fullName>
                <isActive>false</isActive>
                <label>Características de producto</label>
            </value>
            <value>
                <fullName>Mala experiencia con CNS</fullName>
                <isActive>false</isActive>
                <label>Mala experiencia con CNS</label>
            </value>
            <value>
                <fullName>Mejor oferta otra compañía</fullName>
                <isActive>false</isActive>
                <label>Mejor oferta otra compañía</label>
            </value>
            <value>
                <fullName>No tiene capacidad económica</fullName>
                <isActive>false</isActive>
                <label>No tiene capacidad económica</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Origen_sales__c.field-meta.xml
<CustomField>
    <fullName>Origen_sales__c</fullName>
    <label>Origen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Owner_Opp_sales__c.field-meta.xml
<CustomField>
    <fullName>Owner_Opp_sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Propietario de la oportunidad a generar, según Ejecutivo informado por Analytics</description>
    <label>Responsable Oportunidad</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Ofertas</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Rut_Cliente_sales__c.field-meta.xml
<CustomField>
    <fullName>Rut_Cliente_sales__c</fullName>
    <label>Rut Cliente</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Oferta__c/fields/Vigencia_Oferta_sales__c.field-meta.xml
<CustomField>
    <fullName>Vigencia_Oferta_sales__c</fullName>
    <label>Vigencia Oferta</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/OfferCmpController_Test.cls
/**
 * @File Name          : OfferCmpController_Test.cls
 * @Description        : 
 * @Author             : eayalcor@everis.com
 * @Group              : 
 * @Last Modified By   : eayalcor@everis.com
 * @Last Modified On   : 6/23/2020, 11:07:20 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    6/2/2020   eayalcor@everis.com     Initial Version
**/
@isTest 
public with sharing class OfferCmpController_Test {
    /**
    * @description 
    * @author eayalcor@everis.com | 6/2/2020 
    * @return void 
    **/
    @TestSetup
    static void makeData(){
        Map<String, SObject> mapsObjects = TestFactorySales.populateOrg(); 
        User usr = (User)mapsObjects.get('User');      

        Oferta__c offer = new Oferta__c();
        offer.Name= 'OFERID';
        offer.Ejecutivo_sales__c= '1-9';
        offer.Rut_Cliente_sales__c= '10854082-6';
        offer.Vigencia_Oferta_sales__c= Date.today();
        offer.Familia_Producto_sales__c= 'PLAN PLUS';
        offer.Descripcion_oferta_sales__c = '<p>test</p>';
        offer.Detalle_sales__c = 'Nueva Oferta';
        offer.Origen_sales__c = 'Contact Center';
        offer.AccountId__c = [SELECT Id FROM Account WHERE Rut__c = '10854082-6' LIMIT 1].Id;
        offer.Owner_Opp_sales__c = usr.Id;
        insert offer;

        Product2 p2 = new Product2();
        p2.IsActive = true;
        p2.ProductCode = '801';
        p2.Name = 'Test';
        p2.codigo_producto_sales__c= '2';
        p2.Codigo_Macroproducto_Operacional_sales__c='1';
        p2.tipo_producto_sales__c = 'plan_plus_sales';
        p2.Family = Constants.PLAN_PLUS;

        insert p2;
    }

    /**
    * @description 
    * @author eayalcor@everis.com | 6/2/2020 
    * @return void 
    **/
    @isTest
    static void testGetInitialData(){

        Test.startTest();
        List<Oferta__c> lstOffer = [SELECT Id,Name,AccountId__c,Ejecutivo_sales__c,Rut_Cliente_sales__c,
        Familia_Producto_sales__c,Vigencia_Oferta_sales__c,Motivo_no_interes_sales__c,Estado_Oferta_sales__c FROM Oferta__c LIMIT 1];
        
        OfferCmpController.ResponseData response = OfferCmpController.getInitialData(lstOffer[0].Id);

        Test.stopTest();

        System.assertEquals(lstOffer[0].Name, response.offer.Name);
    }

    /**
    * @description 
    * @author eayalcor@everis.com | 6/2/2020 
    * @return void 
    **/
    @isTest
    static void testRejectOffer(){
        Test.startTest();
        List<Oferta__c> lstOffer = [SELECT Id,Name,AccountId__c,Ejecutivo_sales__c,Rut_Cliente_sales__c,
        Familia_Producto_sales__c,Vigencia_Oferta_sales__c,Motivo_no_interes_sales__c,Estado_Oferta_sales__c FROM Oferta__c LIMIT 1];
        
        List<String> lst = UtilitiesSales.getPicklistData(Oferta__c.Motivo_no_interes_sales__c);

        String response = OfferCmpController.rejectOffer(lstOffer[0].Id,lst[0]);

        Test.stopTest();

        System.assertEquals(Constants.OK, response);
    }

    @isTest
    static void testGenerateOpportunity(){
        Test.startTest();
        List<Oferta__c> lstOffer = [SELECT Id,Name,AccountId__c,Ejecutivo_sales__c,Rut_Cliente_sales__c,
        Familia_Producto_sales__c,Vigencia_Oferta_sales__c,Motivo_no_interes_sales__c,Estado_Oferta_sales__c FROM Oferta__c LIMIT 1];

        String response = OfferCmpController.generateOpportunity(lstOffer[0].Id,'test');

        Test.stopTest();

        System.assertEquals(Constants.OK, response);
    }

}