CNSDEVCOLECT/force-app/main/default/objects/Producto_Banco__c/Producto_Banco__c.object-meta.xml
<CustomObject>
    <label>Producto de Banco</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de Banco</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_Banco__c/fields/Id_Interno_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Id_Interno_Nectia__c</fullName>
    <externalId>true</externalId>
    <label>Id Interno</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Cliente_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_cliente</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Estado_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Nectia__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVA</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>CASTIGO</fullName>
            </value>
            <value>
                <fullName>FORWARD INGRESO</fullName>
            </value>
            <value>
                <fullName>FORWARD MODIFICADO</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>INGRESO</fullName>
            </value>
            <value>
                <fullName>MODIFICADO</fullName>
            </value>
            <value>
                <fullName>No Vigente</fullName>
            </value>
            <value>
                <fullName>VENCIDO</fullName>
            </value>
            <value>
                <fullName>VIGENTE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Producto_de_Banco_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_Banco_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto de Banco</label>
    <referenceTo>Producto_Banco__c</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/CONS_RESTProductoBancoControllerTest.cls
@isTest
public class CONS_RESTProductoBancoControllerTest {
    static testMethod void Test1() {
        Producto_Banco__c  prb=new Producto_Banco__c();
        prb.name='qwer';
        prb.Id_Interno_Nectia__c='123456543';
        insert prb;
        account acc=new account();
        acc.RUT__c='23229614-3';
        acc.name='test';
       
        insert acc;
        string json='{"rut_cliente":"23229614-3",'+
            '"estado":"activo",'+
            '"id_producto":"123456543",'+
            '"nombre_producto":"nombre producto test",'+
            '"id_operacion":"123123123"}';
        test.startTest();
        CONS_EstructuraproductoBanco_JSON  resp=(CONS_EstructuraproductoBanco_JSON) System.JSON.deserialize(json, CONS_EstructuraproductoBanco_JSON.class); 
        CONS_EstructuraproductoBanco_JSON.parse(json);
        CONS_Respuestaproducto_JSON.parse(json);
        list<CONS_EstructuraproductoBanco_JSON> resp1=new list<CONS_EstructuraproductoBanco_JSON>();
        resp1 =new list<CONS_EstructuraproductoBanco_JSON>();
        resp1.add(resp);
        CONS_RESTProductoBancoController.CrearActuaizarproductoclienteBanco(resp1);
        test.stopTest();
        
    }
    static testMethod void Test2() {
        Producto_Banco__c  prb=new Producto_Banco__c();
        prb.name='qwer';
        prb.Id_Interno_Nectia__c='123456543';
        insert prb;
        
        account acc=new account();
        acc.RUT__c='23229614-3';
        acc.name='test';
      
        insert acc;
        
       Producto_del_Cliente__c proc=new Producto_del_Cliente__c();
       proc.Id__c='123123123'; 
        proc.Cliente_Nectia__c=acc.id; 
        proc.RecordTypeId=[select id from RecordType where Name=:'Producto cliente Banco'].id;
        proc.Estado_Nectia__c=''; 
        proc.Producto_de_Banco_Nectia__c=prb.id; 
        proc.Name=prb.name;
       insert proc;
        string json='{"rut_cliente":"23229614-3",'+
            '"estado":"activo",'+
            '"id_producto":"123456543",'+
            '"nombre_producto":"nombre producto test",'+
            '"id_operacion":"123123123"}';
        test.startTest();
        CONS_EstructuraproductoBanco_JSON  resp=(CONS_EstructuraproductoBanco_JSON) System.JSON.deserialize(json, CONS_EstructuraproductoBanco_JSON.class); 
        CONS_EstructuraproductoBanco_JSON.parse(json);
        
        list<CONS_EstructuraproductoBanco_JSON> resp1=new list<CONS_EstructuraproductoBanco_JSON>();
        resp1 =new list<CONS_EstructuraproductoBanco_JSON>();
        resp1.add(resp);
        CONS_RESTProductoBancoController.CrearActuaizarproductoclienteBanco(resp1);
        test.stopTest();
        
    }
    
}