CNSDEVCOLECT/force-app/main/default/objects/Producto_Banco__c/Producto_Banco__c.object-meta.xml
<CustomObject>
    <label>Producto de Banco</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de Banco</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_Banco__c/fields/Tipo_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Nectia__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Banca_Nectia__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boleta De Garantia</fullName>
            </value>
            <value>
                <fullName>Boletas</fullName>
            </value>
            <value>
                <fullName>Comex</fullName>
            </value>
            <value>
                <fullName>Crédito Comercial</fullName>
            </value>
            <value>
                <fullName>Crédito Complementario</fullName>
            </value>
            <value>
                <fullName>Crédito de Consumo</fullName>
            </value>
            <value>
                <fullName>Crédito Especiales</fullName>
            </value>
            <value>
                <fullName>Crédito hipotecario</fullName>
            </value>
            <value>
                <fullName>Crédito Pensionado</fullName>
            </value>
            <value>
                <fullName>Cuenta Corriente</fullName>
            </value>
            <value>
                <fullName>Cuentas Por Cobrar Gop</fullName>
            </value>
            <value>
                <fullName>Cuenta Vista</fullName>
            </value>
            <value>
                <fullName>DAP</fullName>
            </value>
            <value>
                <fullName>Factoring</fullName>
            </value>
            <value>
                <fullName>Forward</fullName>
            </value>
            <value>
                <fullName>Leasing</fullName>
            </value>
            <value>
                <fullName>Línea de crédito</fullName>
            </value>
            <value>
                <fullName>Línea De Sobregiro</fullName>
            </value>
            <value>
                <fullName>Spot</fullName>
            </value>
            <value>
                <fullName>Swap</fullName>
            </value>
            <value>
                <fullName>Tarjeta de crédito</fullName>
            </value>
            <value>
                <fullName>Tarjeta de Débito</fullName>
            </value>
            <value>
                <fullName>Trader</fullName>
            </value>
            <value>
                <fullName>Abono de Remuneraciones</fullName>
                <isActive>false</isActive>
                <label>Abono de Remuneraciones</label>
            </value>
            <value>
                <fullName>Comercio Exterior</fullName>
                <isActive>false</isActive>
                <label>Comercio Exterior</label>
            </value>
            <value>
                <fullName>Compra y Venta de Monedas</fullName>
                <isActive>false</isActive>
                <label>Compra y Venta de Monedas</label>
            </value>
            <value>
                <fullName>Créditos Universales</fullName>
                <isActive>false</isActive>
                <label>Créditos Universales</label>
            </value>
            <value>
                <fullName>Cuenta Preferente</fullName>
                <isActive>false</isActive>
                <label>Cuenta Preferente</label>
            </value>
            <value>
                <fullName>Cuentas para cobrar Gop</fullName>
                <isActive>false</isActive>
                <label>Cuentas para cobrar Gop</label>
            </value>
            <value>
                <fullName>Depósito a Plazo Online</fullName>
                <isActive>false</isActive>
                <label>Depósito a Plazo Online</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Corredora__c/Producto_de_Corredora__c.object-meta.xml
<CustomObject>
    <label>Producto de Corredora</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de Corredora</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Corredora__c/fields/Tipo_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Nectia__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cuenta Inversiones</fullName>
            </value>
            <value>
                <fullName>Cuenta Previsional Régimen A</fullName>
            </value>
            <value>
                <fullName>Cuenta Previsional Régimen B</fullName>
            </value>
            <value>
                <fullName>Cuenta Previsional Depositos Convenidos</fullName>
            </value>
            <value>
                <fullName>Cuenta Demo CCB</fullName>
            </value>
            <value>
                <fullName>Planificación Auto</fullName>
            </value>
            <value>
                <fullName>Planificación Vivienda</fullName>
            </value>
            <value>
                <fullName>Planificación Vacaciones</fullName>
            </value>
            <value>
                <fullName>Planificación Educación</fullName>
            </value>
            <value>
                <fullName>Otra Planificación</fullName>
            </value>
            <value>
                <fullName>Cuenta Internacional</fullName>
            </value>
            <value>
                <fullName>Servicios</fullName>
            </value>
            <value>
                <fullName>APV Flexibles</fullName>
                <isActive>false</isActive>
                <label>APV Flexibles</label>
            </value>
            <value>
                <fullName>Acciones</fullName>
                <isActive>false</isActive>
                <label>Acciones</label>
            </value>
            <value>
                <fullName>Depósitos a Plazo</fullName>
                <isActive>false</isActive>
                <label>Depósitos a Plazo</label>
            </value>
            <value>
                <fullName>Fondos Mutuos</fullName>
                <isActive>false</isActive>
                <label>Fondos Mutuos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/Producto_de_Seguros__c.object-meta.xml
<CustomObject>
    <label>Producto de Seguro</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de Seguro</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/Area_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Area_Nectia__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Hogar</fullName>
            </value>
            <value>
                <fullName>Vida/Ahorro</fullName>
            </value>
            <value>
                <fullName>Vida/Protección</fullName>
            </value>
            <value>
                <fullName>APV</fullName>
            </value>
            <value>
                <fullName>Previsión</fullName>
            </value>
            <value>
                <fullName>Colectivos</fullName>
            </value>
            <value>
                <fullName>Otros Seguros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/Tipo_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Nectia__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area_Nectia__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto Full</fullName>
            </value>
            <value>
                <fullName>Auto Flex</fullName>
            </value>
            <value>
                <fullName>Auto Light</fullName>
            </value>
            <value>
                <fullName>Pérdida Total + Responsabilidad Civil</fullName>
            </value>
            <value>
                <fullName>Responsabilidad Civil</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
            <value>
                <fullName>SOAPEX -Seguro Obligatorio Extranjero</fullName>
            </value>
            <value>
                <fullName>Vehículos Pesados</fullName>
            </value>
            <value>
                <fullName>Hogar Total</fullName>
            </value>
            <value>
                <fullName>Hogar Contenido</fullName>
            </value>
            <value>
                <fullName>VidAhorro Flex</fullName>
            </value>
            <value>
                <fullName>VidAhorro 100</fullName>
            </value>
            <value>
                <fullName>Vida Futura</fullName>
            </value>
            <value>
                <fullName>Protección Activa</fullName>
            </value>
            <value>
                <fullName>Seguro Oncológico</fullName>
            </value>
            <value>
                <fullName>Accidentes Personales</fullName>
            </value>
            <value>
                <fullName>Seguro Deporte</fullName>
            </value>
            <value>
                <fullName>Seguro Viaje</fullName>
            </value>
            <value>
                <fullName>Mascota Protegida</fullName>
            </value>
            <value>
                <fullName>Responsabilidad Civil Múltiple</fullName>
            </value>
            <value>
                <fullName>Empresas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Area_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Area_Nectia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Hogar</fullName>
            </value>
            <value>
                <fullName>Vida/Ahorro</fullName>
            </value>
            <value>
                <fullName>Vida/Protección</fullName>
            </value>
            <value>
                <fullName>APV</fullName>
            </value>
            <value>
                <fullName>Previsión</fullName>
            </value>
            <value>
                <fullName>Colectivos</fullName>
            </value>
            <value>
                <fullName>Otros Seguros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Cliente_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_cliente</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Producto_de_Banco_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_Banco_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Producto de Banco</label>
    <referenceTo>Producto_Banco__c</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Producto_de_Corredora_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_Corredora_Nectia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto de Corredora</label>
    <referenceTo>Producto_de_Corredora__c</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_del_Cliente1</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Producto_de_Seguros_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_Seguros_Nectia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto de Seguros</label>
    <referenceTo>Producto_de_Seguros__c</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_del_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Tipo_de_registro_casos__mdt/Tipo_de_registro_casos__mdt.object-meta.xml
<CustomObject>
    <label>Tipo de registro casos Productos</label>
    <pluralLabel>Tipo de registro casos Productos</pluralLabel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Tipo_de_registro_casos__mdt/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Tipo_de_registro_casos__mdt/fields/Id_Producto__c.field-meta.xml
<CustomField>
    <fullName>Id_Producto__c</fullName>
    <label>Id Producto</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/CONS_Nuevo_Caso_Producto_Controller.cls
public with sharing class CONS_Nuevo_Caso_Producto_Controller {
    public Case nuevoCaso{get;set;}
    public Producto_del_Cliente__c prdCliente{get;set;}
    public Producto_de_Seguros__c seguro{get;set;}
    public Producto_de_Corredora__c corredora{get;set;}
    public Producto_Banco__c banca{get;set;}
    public string IdRecordTypePrd{get;set;}
    public string IdRecordTypeCase{get;set;}
    public string tipoRegistro{get;set;}
    
    private transient Schema.DescribeSObjectResult describe;
    private transient Map<Id, Schema.RecordTypeInfo> rtMapById;
    private transient Map<String, Schema.RecordTypeInfo> rtMapByName;
    public Id recordId;
    private Producto_del_Cliente__c record;
    
    public CONS_Nuevo_Caso_Producto_Controller(ApexPages.StandardController controller) {
        
        this.recordId = controller.getId();
        system.debug(this.recordId);
        this.record = (Producto_del_Cliente__c) controller.getRecord();
        system.debug(this.record);

        prdCliente = [select id, Producto_de_Seguros_Nectia__c, Producto_de_Banco_Nectia__c, Producto_de_Corredora_Nectia__c,RecordTypeId from Producto_del_Cliente__c where Id =: recordId];
        system.debug('prdCliente'+prdCliente);
        IdRecordTypePrd = ApexPages.currentPage().getParameters().get('idTipoRegistro');
        tipoRegistro = [Select DeveloperName from Tipo_de_registro_casos__mdt where Id_Producto__c =: IdRecordTypePrd].DeveloperName;
        IdRecordTypeCase = [Select Id__c from Tipo_de_registro_casos__mdt where Id_Producto__c =: IdRecordTypePrd].Id__c;
        nuevoCaso = new Case();
        if(tipoRegistro == 'Casos_Seguros'){
            //seguro = [Select Id, Area_Nectia__c from Producto_de_Seguros__c Where Id =: prdCliente.Producto_de_Seguros_Nectia__c];
            //nuevoCaso.Valores_Nectia__c = seguro.Area_Nectia__c;
        }
        system.debug('prdCliente.Producto_de_Corredora_Nectia__c'+prdCliente.Producto_de_Corredora_Nectia__c);
        system.debug('tipo de registro'+tipoRegistro);
        if(tipoRegistro == 'Casos_Corredora'){
            corredora = [Select Id, Tipo_Nectia__c from Producto_de_Corredora__c Where Id =: prdCliente.Producto_de_Corredora_Nectia__c];
            nuevoCaso.Valores_Nectia__c = corredora.Tipo_Nectia__c;
        }
        system.debug('producto banco'+ prdCliente.Producto_de_Banco_Nectia__c);
        if(tipoRegistro == 'Casos_Banco'){
            system.debug('entro a casos Banco'+prdCliente.Producto_de_Banco_Nectia__c);
            banca = [Select Id, Tipo_Nectia__c from Producto_Banco__c Where Id =: prdCliente.Producto_de_Banco_Nectia__c];
            system.debug('banca'+banca);
            nuevoCaso.Valores_Nectia__c = banca.Tipo_Nectia__c;
        }
        nuevoCaso.RecordTypeId = IdRecordTypeCase;
        nuevoCaso.AccountId = record.Cliente_Nectia__c;
        nuevoCaso.Producto_del_Cliente_Nectia__c = record.Id;
    }
    public pageReference saveAndClose(){
        System.debug('tipo->'+nuevoCaso.Type);
        if (nuevoCaso.Type != 'Reclamo' && nuevoCaso.Tipo_Auxiliar__c != 'Reclamo'){
            nuevoCaso.Status ='Cerrado';
            nuevoCaso.Comments = 'Caso cerrado en la punta';
            nuevoCaso.Tipo_de_cierre_Nectia__c = 'Caso cerrado en la punta';
            if(tipoRegistro == 'Casos_Banco'){
                nuevoCaso.Subtipo__c = nuevoCaso.Subtipo_Auxiliar__c;
                nuevoCaso.Type = nuevoCaso.Tipo_Auxiliar__c;
                nuevoCaso.Valores_Nectia__c = nuevoCaso.Tipo_de_producto_banco__c;
                nuevoCaso.Sub_estado_Nectia__c = 'Solucionado';
                System.debug('tipo->'+nuevoCaso.Type);
                if(nuevoCaso.ContactId == null){
                    nuevoCaso.ContactId = [Select Id from Contact Where AccountId =: nuevoCaso.AccountId].Id;
                }
            }
            
            if(!test.isRunningTest()){
                try{
                    insert nuevoCaso;
                    pageReference p = new PageReference('/'+nuevoCaso.Id);
                    return p;
                }catch(Exception e){
                    return null;
                }
            }else{
                return null;
            }
        }else{
            //ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Reclamos no deben ser cerrados en la creación');
            //ApexPages.addMessages(myMsg);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Reclamos no deben ser cerrados en la creación','Reclamos no deben ser cerrados en la creación'));
            return null;
        }
    }
    public pageReference saveAndSee(){
        //CÓDIGO NECESARIO PARA QUE SE EJECUTEN LAS REGLAS DE ASIGNACIÓN
        AssignmentRule AR = new AssignmentRule();
        AR = [select id from AssignmentRule where SobjectType = 'Case' and Active = true limit 1];
        
        //Creating the DMLOptions for "Assign using active assignment rules" checkbox
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;
        
        //Setting the DMLOption on Case instance
        nuevoCaso.setOptions(dmlOpts);
        if(tipoRegistro == 'Casos_Banco'){
            nuevoCaso.Subtipo__c = nuevoCaso.Subtipo_Auxiliar__c;
            nuevoCaso.Type = nuevoCaso.Tipo_Auxiliar__c;
            nuevoCaso.Valores_Nectia__c = nuevoCaso.Tipo_de_producto_banco__c;
            
        }
        system.debug('nuevoCaso.Subtipo_Auxiliar__c->'+nuevoCaso.Subtipo_Auxiliar__c);
        system.debug('nuevoCaso.Status->'+nuevoCaso.Status);
        system.debug('nuevoCaso.Tipo_de_medio_de_pago__c->'+nuevoCaso.Tipo_de_medio_de_pago__c);
        if(nuevoCaso.Subtipo_Auxiliar__c == 'Fraude - Desconoce transacción'&& nuevoCaso.Status!='Cerrado'&& 
           (nuevoCaso.Fecha_y_hora_del_evento__c==null||nuevoCaso.Tipo_de_medio_de_pago__c== '' ||nuevoCaso.Tipo_de_moneda__c=='' || nuevoCaso.Monto_reclamado__c==null)){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Para crear el subtipo "Fraude - Desconoce transacción" no puede quedar vacío el campo "Fecha y hora del evento, Tipo de medio de pago, Tipo de moneda, Monto reclamado"'));
              return null;
         }
        if(nuevoCaso.Subtipo_Auxiliar__c == 'Fraude - Desconoce transacción'&& nuevoCaso.Status=='Cerrado'&&nuevoCaso.Monto_recuperado__c==null){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Para cerrar el subtipo "Fraude - Desconoce transacción" no puede quedar vacío el campo "Monto recuperado "'));
              return null;
         }
        if(nuevoCaso.Subtipo_Auxiliar__c == 'Bloqueo Tarjeta'&& nuevoCaso.Status!='Cerrado'&&nuevoCaso.Tipo_de_medio_de_pago__c==null && nuevoCaso.Fecha_y_hora_del_evento__c==null){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Para crear el subtipo " Bloqueo Tarjeta " no puede quedar vacío el campo "Fecha y hora del evento, Tipo de medio de pago"'));
              return null;
         }
        if(nuevoCaso.Subtipo_Auxiliar__c == 'Bloqueo Cuenta'&& nuevoCaso.Status!='Cerrado'&&nuevoCaso.Tipo_de_medio_de_pago__c==null && nuevoCaso.Fecha_y_hora_del_evento__c==null) {
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Para crear el subtipo " Bloqueo Cuenta" no puede quedar vacío el campo "Fecha y hora del evento, Tipo de medio de pago"'));
              return null;
         }        

        if(nuevoCaso.ContactId == null){

            nuevoCaso.ContactId = [Select Id from Contact Where AccountId =: nuevoCaso.AccountId].Id;
        
        }

        if(!test.isRunningTest()){
            try{
                insert nuevoCaso;
                pageReference p = new PageReference('/'+nuevoCaso.Id);
                return p;
            }catch(Exception ex){
                ApexPages.addMessages(ex);
                return null;
            }
        }else{
            return null;
        }
    }
    public pageReference cerrar(){
       //PageReference p = new PageReference('/'+record.id);
       PageReference p = new PageReference('/'+record.Cliente_Nectia__c);
       //pageReference p = new PageReference('/');
       p.setRedirect(true); 
       return p;
       //return null;
    
    }

}