CNSDEVCOLECT/force-app/main/default/objects/Arbol_Comunicaciones__mdt/Arbol_Comunicaciones__mdt.object-meta.xml
<CustomObject>
    <label>Árbol Comunicaciones</label>
    <pluralLabel>Árbol Comunicaciones</pluralLabel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Arbol_Comunicaciones__mdt/fields/Estado_del_caso__c.field-meta.xml
<CustomField>
    <fullName>Estado_del_caso__c</fullName>
    <label>Estado del caso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Arbol_Comunicaciones__mdt/fields/Linea_de_negocio__c.field-meta.xml
<CustomField>
    <fullName>Linea_de_negocio__c</fullName>
    <label>Línea de negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generales</fullName>
                <default>true</default>
                <label>Generales</label>
            </value>
            <value>
                <fullName>Rentas Vitalicias</fullName>
            </value>
            <value>
                <fullName>Transversal</fullName>
            </value>
            <value>
                <fullName>Vida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Arbol_Comunicaciones__mdt/fields/Numero_Linea__c.field-meta.xml
<CustomField>
    <fullName>Numero_Linea__c</fullName>
    <label>Número Linea</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Arbol_Comunicaciones__mdt/fields/Plantilla__c.field-meta.xml
<CustomField>
    <fullName>Plantilla__c</fullName>
    <label>Plantilla</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Arbol_Comunicaciones__mdt/fields/Subestado_del_caso__c.field-meta.xml
<CustomField>
    <fullName>Subestado_del_caso__c</fullName>
    <label>Subestado del caso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sin subestado</fullName>
                <default>true</default>
                <label>Sin subestado</label>
            </value>
            <value>
                <fullName>Solucionado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Desistido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Arbol_Comunicaciones__mdt/fields/Subtipo__c.field-meta.xml
<CustomField>
    <fullName>Subtipo__c</fullName>
    <label>Subtipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atención del Tercero Afectado en Siniestro</fullName>
                <default>true</default>
                <label>Atención del Tercero Afectado en Siniestro</label>
            </value>
            <value>
                <fullName>Atención de Siniestro de Pérdida Parcial</fullName>
            </value>
            <value>
                <fullName>Atención de Siniestro de Pérdida Total</fullName>
            </value>
            <value>
                <fullName>Cambio Dato Contacto</fullName>
            </value>
            <value>
                <fullName>Descuento</fullName>
            </value>
            <value>
                <fullName>Modificación de Póliza</fullName>
            </value>
            <value>
                <fullName>Reclamos Pólizas</fullName>
            </value>
            <value>
                <fullName>Reclamos Siniestros</fullName>
            </value>
            <value>
                <fullName>Rescate</fullName>
            </value>
            <value>
                <fullName>Servicio de Asistencia Vehicular</fullName>
            </value>
            <value>
                <fullName>Sobre Denuncio y Asignación Siniestro</fullName>
            </value>
            <value>
                <fullName>Término de Póliza</fullName>
            </value>
            <value>
                <fullName>Traspaso</fullName>
            </value>
            <value>
                <fullName>Asociadas a Producción Grales</fullName>
            </value>
            <value>
                <fullName>Modificación No Efectuada</fullName>
            </value>
            <value>
                <fullName>No Gestión Beneficio Estatal</fullName>
            </value>
            <value>
                <fullName>No Pago Pensión</fullName>
            </value>
            <value>
                <fullName>Asociadas a Producción S. Vida</fullName>
            </value>
            <value>
                <fullName>Reclamos Siniestros S. Vida</fullName>
            </value>
            <value>
                <fullName>Asociadas a Producción S. Generales</fullName>
            </value>
            <value>
                <fullName>21 dias</fullName>
            </value>
            <value>
                <fullName>Traspaso APV</fullName>
            </value>
            <value>
                <fullName>Devolución Primas</fullName>
            </value>
            <value>
                <fullName>Suspensión de Pagos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Arbol_Comunicaciones__mdt/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consulta</fullName>
                <default>true</default>
                <label>Consulta</label>
            </value>
            <value>
                <fullName>Solicitud</fullName>
            </value>
            <value>
                <fullName>Reclamo</fullName>
            </value>
            <value>
                <fullName>21 dias</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Codigo_Plan_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Plan_Nectia__c</fullName>
    <label>Código Plan</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Esquema_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Esquema_Nectia__c</fullName>
    <label>Esquema</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/L_nea__c.field-meta.xml
<CustomField>
    <fullName>L_nea__c</fullName>
    <formula>TEXT(Producto_de_Seguros_Nectia__r.L_nea__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Línea</label>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Numero_Certificado_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Numero_Certificado_Nectia__c</fullName>
    <label>Número Certificado</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Poliza_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Poliza_Nectia__c</fullName>
    <externalId>true</externalId>
    <label>Nº Poliza</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Ramo_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Ramo_Nectia__c</fullName>
    <label>Ramo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Rut_del_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Rut_del_Cliente__c</fullName>
    <formula>Cliente_Nectia__r.RUT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rut del Cliente</label>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/CONS_Comunicaciones.cls
public class CONS_Comunicaciones {
    public String idcas{get;set;}
    public String urlSF{get;set;}
    public CONS_Comunicaciones() {
        urlSF = URL.getSalesforceBaseUrl().toExternalForm()+'/';
        idcas = ApexPages.currentPage().getParameters().get('id');
        
    }
    public PageReference endosocomunicaciones(){
          system.debug('endoso comunicaciones'); 
        idcas = ApexPages.currentPage().getParameters().get('id');
        case cas=[select id,Accountid,Account.Name,Account.FirstName,Account.lastName,Producto_del_Cliente_Nectia__c,Rut_del_Cliente__c,Seguros_producto__c,Linea_Producto_Seguros__c,
                  V_a_de_Pago__c,D_a_de_Pago__c,Account.PersonBirthdate,Account.Genero_Nectia__pc,Account.PersonEmail,Tipo_de_cuenta__c,CaseNumber,Banco__c,Mensaje_Transaci_n__c,
                  CreatedDate,N_mandato__c,CreatedByid,Fecha_de_Vigencia_de_Tarjeta_Nectia__c,Fecha_Vencimiento_Tarjeta__c,type,Subtipo__c,Tel_fono_de_contacto__c from case where id=:idcas];
        system.debug('cas='+cas);
        string userid=UserInfo.getUserId();
        system.debug('userid'+userid);
        /*user  us=[select id,Codigo_Usuario_Nectia__c  from user where id=:userid];
        system.debug('us='+us);*/
        Producto_del_Cliente__c pro=[select id,Codigo_Plan_Nectia__c,Poliza_Nectia__c,Numero_Certificado_Nectia__c,Esquema_Nectia__c,Ramo_Nectia__c,L_nea__c
                                     from Producto_del_Cliente__c where id=:cas.Producto_del_Cliente_Nectia__c];
        system.debug('pro='+pro);
         Arbol_Comunicaciones__mdt   arcom;
        try{
           arcom=[SELECT Numero_Linea__c, Id, Tipo__c, Subtipo__c, Plantilla__c, Estado_del_caso__c, Subestado_del_caso__c,Linea_de_negocio__c 
                                           FROM Arbol_Comunicaciones__mdt  where   Tipo__c=:cas.type  and Subtipo__c=:cas.Subtipo__c 
                                            and Estado_del_caso__c=:'Nuevo' and Linea_de_negocio__c=:pro.L_nea__c limit 1];
        system.debug('arcom='+arcom);
        }catch(Exception e){
            arcom=null;
        }


        CONS_EndosoComunicaciones_JSON  ed=new CONS_EndosoComunicaciones_JSON();
        ed.nCelular=(cas.Tel_fono_de_contacto__c==null?'':cas.Tel_fono_de_contacto__c);   //opcional
        ed.nNumMandato=(cas.N_mandato__c==null?'':cas.N_mandato__c);         //opcional
        ed.nNumpoliza=pro.Poliza_Nectia__c;                                            //Obligatorio
        ed.nNumsolicitud=string.valueOf(integer.valueOf(cas.CaseNumber));               //Obligatorio
        ed.nResolucionCaso='';              //opcional
        ed.nTelefonoEjec='';                 //opcional
        ed.sBanco=cas.Banco__c;               //Obligatorio
        ed.sDoc_Adjunto='';                              //opcional
        ed.sEmail=cas.Account.PersonEmail;               //opcional
        ed.sFechaCierre='';                              //opcional
        ed.sFechaEfectivaEndoso='';                      //opcional
        DateTime d = cas.CreatedDate ;
        String dateStr =  d.format('dd-MM-yyyy') ;
        ed.sFechaRecepcion=dateStr;                     //opcional
        if(arcom!=null){
        ed.sLinNegocio= arcom.Linea_de_negocio__c;    //Obligatorio
        ed.nNegocio=arcom.Numero_Linea__c;            //Obligatorio
         ed.sPlantilla=arcom.Plantilla__c;            //Obligatorio
        }else{
           ed.sLinNegocio='';       //Obligatorio
        ed.nNegocio='';             //Obligatorio
         ed.sPlantilla='';          //Obligatorio
        }
        ed.sMailEjecutivo='';            //opcional
        ed.sMotivoRechazo='';          //opcional
        ed.sNomEjecutivo='';          //opcional
        ed.sNombcaso=cas.Type+'-'+cas.Subtipo__c;       //Obligatorio
        ed.sNombreCliente=cas.Account.Name;     //Obligatorio
       
        string envio =JSON.serialize(ed);
        system.debug('envio estructura salesforce= '+envio);
        /* envio='{'+
'"nCelular":"999999",'+
'"nNumMandato":"",'+
'"nNumpoliza":"12345",'+
'"nNumsolicitud":"435",'+
'"nResolucionCaso":"",'+
'"nTelefonoEjec":"",'+
'"sBanco":"",'+
'"sDoc_Adjunto":"",'+
'"sEmail":"dgaticapizarro@gmail.com",'+
'"sFechaCierre":"",'+
'"sFechaEfectivaEndoso":"",'+
'"sFechaRecepcion":"20-01-2019",'+
'"sLinNegocio":"1",'+
'"nNegocio":"1",'+
'"sMailEjecutivo":"dgaticapizarro@gmail.com",'+
'"sMotivoRechazo":"",'+
'"sNomEjecutivo":"",'+
'"sNombcaso":"caso 1",'+
'"sNombreCliente":"Diego",'+
'"sPlantilla":"PLA0000011"'+
'}';*/
        Cons_callOutService  call= new Cons_callOutService();
        string token=call.callOuttoken();
        system.debug('token'+token);
        CONS_token_JSON tok = (CONS_token_JSON)JSON.deserialize(token,CONS_token_JSON.class);  
        system.debug('token=='+tok.access_token);
        string str='';
        if(pro.Esquema_Nectia__c=='INSUDB'){
            if( !test.isrunningtest()){ 
      str=call.callOutEndoso_Comunicaciones_Vida(tok.access_token,envio,null); 
            } 
        }else if(pro.Esquema_Nectia__c=='CLONINSUDB'){
          str= call.callOutEndoso_Comunicaciones_Generales(tok.access_token,envio,null);
        }else if(pro.Esquema_Nectia__c=='SISRVOWCNS'|| pro.Esquema_Nectia__c=='SISRVOWPCNS' || pro.Esquema_Nectia__c=='SISRVOWCNL'){
        //    str= call.callOutEndoso_Comunicaciones_RV(tok.access_token,envio);
                   system.debug('no esxiste servicio disponible');
        }
        system.debug('respuesta del servicio '+str);
        cas.Mensaje_Transaci_n__c=str;
        update cas;
        PageReference p = new PageReference('/'+idcas);
        p.setRedirect(true);
        return null;
        
        
    }
    
    public  PageReference continuar(){
        system.debug('entro a continuar'); 
        PageReference p = new PageReference('/'+idcas);
        p.setRedirect(true);
        return p;
    }
}