CNSDEVCOLECT/force-app/main/default/objects/InformativoEEVV__mdt/InformativoEEVV__mdt.object-meta.xml
<CustomObject>
    <description>Sección para entregar información relevante a los EEVV</description>
    <label>Informativo EEVV</label>
    <pluralLabel>Informativo</pluralLabel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/VisualizarTab__c/VisualizarTab__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CS parametrizable, para indicar que perfiles pueden visualizar la tab de informaciones.</description>
    <label>Visualizar Tab</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/VisualizarTab__c/fields/Visualizar__c.field-meta.xml
<CustomField>
    <fullName>Visualizar__c</fullName>
    <defaultValue>false</defaultValue>
    <description>El perfil ingresado debe tener el check activado para poder visualizar la tab</description>
    <label>Visualizar</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/SectionInfoController_Test.cls
@isTest
private class SectionInfoController_Test {

    @TestSetup
    static void makeData(){
        List<User> makeUser = new List<User>();
        User user1 = TestFactorySales.createUser('19', Constants.PROFILE_EJECUTIVO_VENTA, 'TSInfo1');
        user1.Modelo_Comercial__c = 'FFVV Seguros Nueva';
        makeUser.add(user1);
        makeUser.add(TestFactorySales.createUser('28', Constants.PROFILE_JEFE_CAMPANA, 'TSInfo2'));

        insert makeUser;
    }

    @isTest
    static void getSectionInfoOK() {
        Test.startTest();
        Boolean isVisible = false;
        List<InformativoEEVV__mdt> lstMeta = new List<InformativoEEVV__mdt>();
        lstMeta = SectionInfoController.getSectionInfo();
        if(lstMeta.size() > 0){
            isVisible = true;
        }
        System.assertEquals(true, isVisible);
        Test.stopTest();
    }

    @isTest
    static void hasAccessTest(){
        List<User> lstUser = [SELECT Id,Modelo_Comercial__c FROM User WHERE Rut__c = '19'];

        upsert new VisualizarTab__c(SetupOwnerId=lstUser[0].Id,Visualizar__c = true);
        
        System.runAs(lstUser[0]){
            Test.startTest();
            Boolean testValue = SectionInfoController.hasAccess();

            System.assertEquals(false, testValue);
            Test.stopTest();
        }
    }
}