CNSDEVCOLECT/force-app/main/default/objects/InformativoEEVV__mdt/InformativoEEVV__mdt.object-meta.xml
<CustomObject>
    <description>Sección para entregar información relevante a los EEVV</description>
    <label>Informativo EEVV</label>
    <pluralLabel>Informativo</pluralLabel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/InformativoEEVV__mdt/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Descripción de la sección a crear</description>
    <label>Descripción</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/InformativoEEVV__mdt/fields/Titulo__c.field-meta.xml
<CustomField>
    <fullName>Titulo__c</fullName>
    <description>Titulo referente a la sección a agregar</description>
    <label>Titulo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/InformativoEEVV__mdt/fields/URL_informativa__c.field-meta.xml
<CustomField>
    <fullName>URL_informativa__c</fullName>
    <description>Url para rederigir a más información del ejecutivo</description>
    <label>URL informativa</label>
    <type>Url</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/VisualizarTab__c/VisualizarTab__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CS parametrizable, para indicar que perfiles pueden visualizar la tab de informaciones.</description>
    <label>Visualizar Tab</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/VisualizarTab__c/fields/Visualizar__c.field-meta.xml
<CustomField>
    <fullName>Visualizar__c</fullName>
    <defaultValue>false</defaultValue>
    <description>El perfil ingresado debe tener el check activado para poder visualizar la tab</description>
    <label>Visualizar</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/SectionInfoController.cls
public without sharing class SectionInfoController {

    private static final String MODELO_MARCA_COMERCIAL = 'FFVV Seguros Nueva';

    @AuraEnabled(cacheable=true)
    public static List<InformativoEEVV__mdt> getSectionInfo(){

        List<InformativoEEVV__mdt> lstMetadata = [SELECT Titulo__c,Descripcion__c,URL_informativa__c 
        FROM InformativoEEVV__mdt];

        return lstMetadata;
    }

    @AuraEnabled(cacheable=true)
    public static Boolean hasAccess(){

        Boolean access = false;

        List<User> lstUser = [SELECT Id,Modelo_Comercial__c FROM User WHERE Id =: UserInfo.getUserId()];

        if(lstUser[0].Modelo_Comercial__c != null && (lstUser[0].Modelo_Comercial__c.equalsIgnoreCase(MODELO_MARCA_COMERCIAL) && 
            VisualizarTab__c.getInstance(UserInfo.getProfileId()).Visualizar__c )){
            access = true;
        }

        return access;
    }
}