CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/participante_sales__c.object-meta.xml
<CustomObject>
    <label>Participante</label>
    <nameField>
        <label>Nombre Participante</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/estado_participante_sales__c.field-meta.xml
<CustomField>
    <fullName>estado_participante_sales__c</fullName>
    <description>Campo para indicar si el participante aún forma parte o no del crédito hipotecario.</description>
    <label>Estado Participante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>No Vigente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/opportunity_participante_sales__c.field-meta.xml
<CustomField>
    <fullName>opportunity_participante_sales__c</fullName>
    <description>Campo que relaciona el objeto Participante con el objeto Oportunidad.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>participantes_sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/remuneracion_sales__c.field-meta.xml
<CustomField>
    <fullName>remuneracion_sales__c</fullName>
    <label>Remuneración</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/rut_sales__c.field-meta.xml
<CustomField>
    <fullName>rut_sales__c</fullName>
    <description>Campo para almacenar el rut del participante de hipotecario.</description>
    <label>Rut</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/telefono_movil_sales__c.field-meta.xml
<CustomField>
    <fullName>telefono_movil_sales__c</fullName>
    <description>Campo para almacenar el número móvil del participante de hipotecario.</description>
    <label>Teléfono Móvil</label>
    <type>Phone</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/tipo_documento_sales__c.field-meta.xml
<CustomField>
    <fullName>tipo_documento_sales__c</fullName>
    <label>Tipo Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/ActivateParticipantControllerTest.cls
@isTest
public class ActivateParticipantControllerTest {
    @testSetup static void setup() {
        Test.startTest();
        List<User> userList = new List<User>();
        Map<String, SObject> mapsOppObjects = new Map<String, SObject>();
        TestFactorySales.createConsorcioOrg();
        // Create User Ejecutivo Especialista
        User user01 = TestFactorySales.createUser('222222222', CONSTANTS.PROFILE_EJECUTIVO_ESPECIALISTA, 'USERESP');
        userList.add(user01);
        
        insert userList;
        
        // Create Account object
        //Account acc01 = TestFactorySales.createNewAccount('11111111-1', 'Cliente');
        Account acc01 = TestFactorySales.createNewAccountWithOwner('11111111-1', 'Cliente', user01.id);

        
        // Create Opp with products
        Id idProd2 = Test.getStandardPricebookId();
        mapsOppObjects = TestFactorySales.createOpportunityWithProductContact(idProd2, acc01.id, user01.id);
        
        Opportunity opp = (Opportunity) mapsOppObjects.get('Opportunity');

        participante_sales__c par = new participante_sales__c();
        par.rut_sales__c='21484503-2';
        par.tipo_documento_sales__c='RUT';
        par.Name='dino';
        par.remuneracion_sales__c=5000000;
        par.telefono_movil_sales__c='828081865';
        par.estado_participante_sales__c='Vigente';
        par.opportunity_participante_sales__c = opp.Id;
        insert par; 
        Test.stopTest();
    }
    
    @isTest
    public static void testActivateParticipant() {
        Test.startTest();
        User user01 = TestFactorySales.createUser('222222244', CONSTANTS.PROFILE_EJECUTIVO_ESPECIALISTA, 'USERESP2');
        
        insert user01;
        participante_sales__c par = [SELECT Id FROM participante_sales__c LIMIT 1];
        ActivateParticipantController.getInitialData(par.Id); 
        
        system.runAs(user01){
            System.assertNotEquals(par, null);
        }
        Test.stopTest(); 
        
    }
    
	
    @isTest
    public static void testActivateOppParticipant() {
        Test.startTest();
        String result;
        User user01 = [select id, alias,profileid from User Where Alias = 'USERESP'];
        participante_sales__c par = [SELECT Id FROM participante_sales__c LIMIT 1];
        system.runAs(user01){
            result = ActivateParticipantController.activateOppParticipant(par.Id); 
             System.assertEquals(CONSTANTS.OK, result);
        }
        system.runAs(user01){
            result = ActivateParticipantController.activateOppParticipant(user01.Id); 
             System.assertEquals(CONSTANTS.PARTICIPANT_ERROR1, result);
        }
        

        Test.stopTest();   
       
    }
    
    @isTest
    public static void testDeactivateOppParticipant(){
        Test.startTest();
        String result;
        User user01 = [select id, alias,profileid from User Where Alias = 'USERESP'];
        participante_sales__c par = [SELECT Id FROM participante_sales__c LIMIT 1];
        system.runAs(user01){
            result = ActivateParticipantController.deactivateOppParticipant(par.Id, 'Rechazado por riesgo');
        }
        Test.stopTest(); 
        System.assertEquals(CONSTANTS.OK, result);
    }
    
}