CNSDEVCOLECT/force-app/main/default/objects/TaskInformation__c/TaskInformation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Información para generar tareas</description>
    <label>TaskInformation</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/TaskInformation__c/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <label>Asunto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/TaskInformation__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/TaskInformation__c/fields/Filtro__c.field-meta.xml
<CustomField>
    <fullName>Filtro__c</fullName>
    <label>Filtro</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/TaskInformation__c/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <label>Origen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/TaskInformation__c/fields/Tipo_Notificacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Notificacion__c</fullName>
    <description>Se define el tipo de notificación</description>
    <label>Tipo Notificación</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/TaskInformation__c/fields/ValorFiltro__c.field-meta.xml
<CustomField>
    <fullName>ValorFiltro__c</fullName>
    <label>ValorFiltro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/TaskInformation__c/fields/Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Vencimiento__c</fullName>
    <label>Vencimiento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/TaskTriggerPFHelper.cls
/*********************************************************************************************************
@Author       gcabrerp@everis.com
@name         TaskTriggerPFHelper
@CreateDate   18/11/2020
@Description  Helper of the Task object
***********************************************************************************************************
History of changes: 
-----------------------------------------------------------------------------------------------------------
Date          Developer                     Comments   
-----------------------------------------------------------------------------------------------------------
**********************************************************************************************************/
public with sharing class TaskTriggerPFHelper {
    public static List<TaskInformation__c> lstTask  {get; set;}
    private static Map<String,TaskInformation__c> taskMap;   
    private final static String PF_RECORD_TYPE = Label.PF_Opp_RecordType;
    
    public static List<TaskInformation__c> loadSettings(){
        if(lstTask == null){
            lstTask = [select  Name, Asunto__c, Estado__c, Origen__c, Vencimiento__c, Filtro__c, ValorFiltro__c, Tipo_Notificacion__c from TaskInformation__c where Origen__c =: PF_RECORD_TYPE];
        }
        taskMap = new Map<String,TaskInformation__c>();
        for(TaskInformation__c tsk:lstTask){
            taskMap.put(tsk.ValorFiltro__c, tsk);
        }
        return lstTask;
    }
    
    public static void onAfterUpdate(List<Task> newTaskList, List<Task> oldTaskList){
        loadSettings();
        try{
            for (Task o: oldTaskList) {
                    for (Task t: newTaskList) {
                        String ss = t.who.FirstName;
                       if(o.Status == 'Abierta' && t.Status == taskMap.get('Tarea_Completa').Estado__c && (t.Subject == taskMap.get('Sol_Firmada_PF__c').Asunto__c || t.Subject== taskMap.get('CAD').Asunto__c)){
                            CnsCustomNotification.notifyCurrentUser(JSON.serialize(t), taskMap.get('Tarea_Completa').Tipo_Notificacion__c, new List<String>{t.PF_Opportunity_Owner__c});
                        }
                    }
            }
        }catch(Exception e){e.setMessage('Ha ocurrido un error, informe a un administrador :'+e.getCause());}
    }
}