CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Cliente_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_cliente</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Estado_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Nectia__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVA</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>CASTIGO</fullName>
            </value>
            <value>
                <fullName>FORWARD INGRESO</fullName>
            </value>
            <value>
                <fullName>FORWARD MODIFICADO</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>INGRESO</fullName>
            </value>
            <value>
                <fullName>MODIFICADO</fullName>
            </value>
            <value>
                <fullName>No Vigente</fullName>
            </value>
            <value>
                <fullName>VENCIDO</fullName>
            </value>
            <value>
                <fullName>VIGENTE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Tipo_de_registro_casos__mdt/Tipo_de_registro_casos__mdt.object-meta.xml
<CustomObject>
    <label>Tipo de registro casos Productos</label>
    <pluralLabel>Tipo de registro casos Productos</pluralLabel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Tipo_de_registro_casos__mdt/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Tipo_de_registro_casos__mdt/fields/Id_Producto__c.field-meta.xml
<CustomField>
    <fullName>Id_Producto__c</fullName>
    <label>Id Producto</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/relatedProductsExtension.cls
public with sharing class relatedProductsExtension {

    public List<Producto_del_Cliente__c> listaProductos{get;set;}
    public Account accId{get;set;}
    public String tipoRegistroPrd{get;set;}
    public String tipoRegistroCaso{get;set;}
    public String idProducto{get;set;}
    public String nombreCliente{get;set;}
    public relatedProductsExtension(ApexPages.StandardController controller) {
        accId = (Account)controller.getRecord();
        nombreCliente = [Select Id, Name from Account Where id =: accId.Id].Name;
        listaProductos = [Select Id, Name, Estado_Nectia__c, RecordTypeId from Producto_del_Cliente__c where Cliente_Nectia__c =: accId.Id];
        
    }

    public void crearCaso(){
        //https://bcoconsorcio--devbancorr.cs71.my.salesforce.com/500/e?ent=Case&cas4=Nectia&RecordType=0124D000000CjJL&CF00N4D000000Tc81=Hogar%20Full%2015954778-7&retURL=%2F500%2Fo
        PageReference p; 
        system.debug(tipoRegistroPrd);
        if(!test.isRunningTest()){
        tipoRegistroCaso = [Select Id__c  from Tipo_de_registro_casos__mdt where Id_Producto__c =: tipoRegistroPrd].Id__c;
        }
        system.debug(tipoRegistroCaso);
        p = new PageReference('/apex/CONS_Nuevo_Caso_Producto?id='+idProducto+'&idTipoRegistro='+tipoRegistroCaso);
            
        system.debug(p);
         
        //return p;
    }   
    
    
    
}