CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Codigo_Plan_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Plan_Nectia__c</fullName>
    <label>Código Plan</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Esquema_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Esquema_Nectia__c</fullName>
    <label>Esquema</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Numero_Certificado_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Numero_Certificado_Nectia__c</fullName>
    <label>Número Certificado</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Poliza_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Poliza_Nectia__c</fullName>
    <externalId>true</externalId>
    <label>Nº Poliza</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Ramo_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Ramo_Nectia__c</fullName>
    <label>Ramo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Tipo_Registro_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Registro_Nectia__c</fullName>
    <label>Tipo Registro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/CONS_Visualizar_Multiconsultaproducto.cls
public class CONS_Visualizar_Multiconsultaproducto {
    public string url {get;set;}
    public string idpro {get;set;}
    public CONS_Visualizar_Multiconsultaproducto(ApexPages.StandardController  controller) {
        idpro = controller.getId();
        Producto_del_Cliente__c pro=[select id, Poliza_Nectia__c,Tipo_Registro_Nectia__c,Ramo_Nectia__c,Codigo_Plan_Nectia__c,Numero_Certificado_Nectia__c,Esquema_Nectia__c 
                                     from Producto_del_Cliente__c where id=:idpro limit 1];
        string aplicacion='';
         boolean issandbox = [SELECT Id, InstanceName, IsSandbox FROM Organization limit 1].IsSandbox;
        if(issandbox==true){
           /* if(pro.Esquema_Nectia__c=='INSUDB'){
                aplicacion='MULCONCCV'; 
            }else if(pro.Esquema_Nectia__c=='CLONINSUDB'){
                aplicacion='MULCONCCG';
            }else if(pro.Esquema_Nectia__c=='VTCNLIFE'){
                aplicacion='MULCONCCNL';
            }  */      
       		//url='http://aplicacionesqa.cnsv.cl/ConsultasPolizas/loginCRM.asp?sCertype=2&nBranch=1&nProduct=650&nPolicy=11514904&nCertif=0&sAplicacion=MULCONCCVB';
        	url='http://aplicacionesqa.cnsv.cl/ConsultasPolizas/loginCRM.asp?sCertype=2&nBranch='+pro.Ramo_Nectia__c+'&nProduct='+pro.Codigo_Plan_Nectia__c+'&nPolicy='+pro.Poliza_Nectia__c+'&nCertif='+pro.Numero_Certificado_Nectia__c+'&sAplicacion=MULCONCCVB';    
       		// url='https://aplicacionesqa.cnsv.cl/ConsultasPolizas/loginCRM.asp?sCertype=2&nBranch='+pro.Ramo_Nectia__c+'&nProduct='+pro.Codigo_Plan_Nectia__c+'&nPolicy='+pro.Poliza_Nectia__c+'&nCertif='+pro.Numero_Certificado_Nectia__c+'&sAplicacion='+aplicacion;
        }else {
           //MJV - Comentado para pasar a sandbox devcns
         /*   if(pro.Esquema_Nectia__c=='INSUDB'){
            	aplicacion='MULTICONVIDA'; 
            }else if(pro.Esquema_Nectia__c=='CLONINSUDB'){
                aplicacion='MULTICONGRAL';
            }else if(pro.Esquema_Nectia__c=='VTCNLIFE'){
                aplicacion='MULTICONCNLI';
            }  */      
            url='http://aplicaciones.cnsv.cl/ConsultasPolizas/loginCRM.asp?sCertype=2&nBranch='+pro.Ramo_Nectia__c+'&nProduct='+pro.Codigo_Plan_Nectia__c+'&nPolicy='+pro.Poliza_Nectia__c+'&nCertif='+pro.Numero_Certificado_Nectia__c+'&sAplicacion=MULCONCCVB';
           
        }
        system.debug('url==>'+url);
        }    
      public PageReference  continuar(){
        system.debug('idpro'+idpro);
        pageReference p = new PageReference('/'+idpro);
        return p;
          
      }
}