CNSDEVCOLECT/force-app/main/default/objects/Linea_Bancaria__c/Linea_Bancaria__c.object-meta.xml
<CustomObject>
    <label>Línea Bancaria</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Líneas Bancarias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Linea_Bancaria__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Líneas Bancarias</relationshipLabel>
    <relationshipName>LineasBancarias</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Linea_Bancaria__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banco Bice</fullName>
            </value>
            <value>
                <fullName>Banco BTG Pactual Chile</fullName>
            </value>
            <value>
                <fullName>Banco Consorcio</fullName>
            </value>
            <value>
                <fullName>Banco de Chile</fullName>
            </value>
            <value>
                <fullName>Banco de Crédito e Inversiones</fullName>
            </value>
            <value>
                <fullName>Banco del Estado de Chile</fullName>
            </value>
            <value>
                <fullName>Banco do Brasil S.A.</fullName>
            </value>
            <value>
                <fullName>Banco Falabella</fullName>
            </value>
            <value>
                <fullName>Banco Internacional</fullName>
            </value>
            <value>
                <fullName>Banco Ripley</fullName>
            </value>
            <value>
                <fullName>Banco Santander-Chile</fullName>
            </value>
            <value>
                <fullName>Banco Security</fullName>
            </value>
            <value>
                <fullName>Bank of China, Agencia en Chile</fullName>
            </value>
            <value>
                <fullName>China Construction Bank, Agencia en Chile</fullName>
            </value>
            <value>
                <fullName>HSBC Bank (Chile)</fullName>
            </value>
            <value>
                <fullName>Itaú Corpbanca</fullName>
            </value>
            <value>
                <fullName>JP Morgan Chase Bank, N.A.</fullName>
            </value>
            <value>
                <fullName>Scotiabank Chile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Linea_Bancaria__c/fields/Id_Prospecto__c.field-meta.xml
<CustomField>
    <fullName>Id_Prospecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospecto</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Líneas Bancarias</relationshipLabel>
    <relationshipName>Lineas_Bancarias</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Linea_Bancaria__c/fields/Monto_Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Monto_Aprobado__c</fullName>
    <label>Monto Aprobado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Linea_Bancaria__c/fields/Monto_Utilizado__c.field-meta.xml
<CustomField>
    <fullName>Monto_Utilizado__c</fullName>
    <description>Monto utilizado en línea bancaria</description>
    <label>Monto Utilizado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/LineaBancariaHelperB2b.cls
/**
 * @description       : 
 * @author            : ggonzroj@everis.com
 * @group             : 
 * @last modified on  : 10-29-2020
 * @last modified by  : ggonzroj@everis.com
 * Modifications Log 
 * Ver   Date         Author                Modification
 * 1.0   08-21-2020   ggonzroj@everis.com   Initial Version
**/
public with sharing class LineaBancariaHelperB2b {
    public static String PKL_BANCO_CONSORCIO = 'Banco Consorcio';
    
    /**
      * @description       This method return list with the Linea_Bancaria__c Records
      * @param1            Set<Id> Id del prospecto
      * @return            List Linea_Bancaria__c
    */
    public static List<Linea_Bancaria__c> getLineasBancariasByLeadId(Set<Id> idsLeads){
        return [SELECT Id, Id_Prospecto__c, Banco__c, Monto_Aprobado__c, Monto_Utilizado__c FROM Linea_Bancaria__c WHERE Id_Prospecto__c IN: idsLeads];
    }

    /*
    * @Author          :   Georvys Gonzalez <ggonzroj@everis.com>
    * @Description     :   Helper Map de Account con lista de Linea_Bancaria__c relacionadas.
    */
    public static Map<Id, List<Linea_Bancaria__c>> getlineasBancariaByAccount (Set<Id> accountds) {
        Map<Id, List<Linea_Bancaria__c>> lbacnariasMap = new Map<Id, List<Linea_Bancaria__c>>();
        for (Linea_Bancaria__c linea : [SELECT Id, Id_Prospecto__c, Banco__c, Account__c,
                                            Monto_Aprobado__c, Monto_Utilizado__c
                                        FROM Linea_Bancaria__c 
                                        WHERE Account__c IN: accountds]){
            if (!lbacnariasMap.containsKey(linea.Account__c)) {
                lbacnariasMap.put(linea.Account__c, new List<Linea_Bancaria__c> {linea});
            } else {
                lbacnariasMap.get(linea.Account__c).add(linea);
            }
        }
        return lbacnariasMap;
    }

    /*
    * @Author          :   Georvys Gonzalez <ggonzroj@everis.com>
    * @Description     :   Helper Map de Account con lista de Linea_Bancaria__c relacionadas.
    */
    public static Map<Id, List<Linea_Bancaria__c>> getlineasBancariaByLead (Set<Id> leadIds) {
        Map<Id, List<Linea_Bancaria__c>> lbacnariasMap = new Map<Id, List<Linea_Bancaria__c>>();
        for (Linea_Bancaria__c linea : [SELECT Id, Id_Prospecto__c, Banco__c, Account__c,
                                                Monto_Aprobado__c, Monto_Utilizado__c, OwnerId
                                        FROM Linea_Bancaria__c 
                                        WHERE Id_Prospecto__c IN: leadIds ]){
            if (!lbacnariasMap.containsKey(linea.Id_Prospecto__c)) {
                lbacnariasMap.put(linea.Id_Prospecto__c, new List<Linea_Bancaria__c> {linea});
            } else {
                lbacnariasMap.get(linea.Id_Prospecto__c).add(linea);
            }
        }
        return lbacnariasMap;
    }

}