CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Corredora__c/Producto_de_Corredora__c.object-meta.xml
<CustomObject>
    <label>Producto de Corredora</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de Corredora</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Corredora__c/fields/Codigo_de_producto_corredora__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_producto_corredora__c</fullName>
    <externalId>true</externalId>
    <label>Código de producto corredora</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Corredora__c/fields/Estado_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Nectia__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Corredora__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <label>Producto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Tipo_Nectia__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Acciones</fullName>
            </value>
            <value>
                <fullName>Fondos Mutuos</fullName>
            </value>
            <value>
                <fullName>Depósitos a Plazo</fullName>
            </value>
            <value>
                <fullName>ETF</fullName>
            </value>
            <value>
                <fullName>Fondos de Inversión</fullName>
            </value>
            <value>
                <fullName>Renta Fija</fullName>
            </value>
            <value>
                <fullName>Simultáneas</fullName>
            </value>
            <value>
                <fullName>Sitio News</fullName>
            </value>
            <value>
                <fullName>Profundidad de Mercado</fullName>
            </value>
            <value>
                <fullName>Alarmas</fullName>
            </value>
            <value>
                <fullName>Analisis Técnico</fullName>
            </value>
            <value>
                <fullName>Información de Mercado</fullName>
            </value>
            <value>
                <fullName>Servicio Emaling</fullName>
            </value>
            <value>
                <fullName>Pactos</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Corredora__c/fields/Tipo_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Nectia__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cuenta Inversiones</fullName>
            </value>
            <value>
                <fullName>Cuenta Previsional Régimen A</fullName>
            </value>
            <value>
                <fullName>Cuenta Previsional Régimen B</fullName>
            </value>
            <value>
                <fullName>Cuenta Previsional Depositos Convenidos</fullName>
            </value>
            <value>
                <fullName>Cuenta Demo CCB</fullName>
            </value>
            <value>
                <fullName>Planificación Auto</fullName>
            </value>
            <value>
                <fullName>Planificación Vivienda</fullName>
            </value>
            <value>
                <fullName>Planificación Vacaciones</fullName>
            </value>
            <value>
                <fullName>Planificación Educación</fullName>
            </value>
            <value>
                <fullName>Otra Planificación</fullName>
            </value>
            <value>
                <fullName>Cuenta Internacional</fullName>
            </value>
            <value>
                <fullName>Servicios</fullName>
            </value>
            <value>
                <fullName>APV Flexibles</fullName>
                <isActive>false</isActive>
                <label>APV Flexibles</label>
            </value>
            <value>
                <fullName>Acciones</fullName>
                <isActive>false</isActive>
                <label>Acciones</label>
            </value>
            <value>
                <fullName>Depósitos a Plazo</fullName>
                <isActive>false</isActive>
                <label>Depósitos a Plazo</label>
            </value>
            <value>
                <fullName>Fondos Mutuos</fullName>
                <isActive>false</isActive>
                <label>Fondos Mutuos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Cliente_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_cliente</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Estado_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Nectia__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVA</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>CASTIGO</fullName>
            </value>
            <value>
                <fullName>FORWARD INGRESO</fullName>
            </value>
            <value>
                <fullName>FORWARD MODIFICADO</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>INGRESO</fullName>
            </value>
            <value>
                <fullName>MODIFICADO</fullName>
            </value>
            <value>
                <fullName>No Vigente</fullName>
            </value>
            <value>
                <fullName>VENCIDO</fullName>
            </value>
            <value>
                <fullName>VIGENTE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Fecha_de_apertura_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_apertura_Nectia__c</fullName>
    <label>Fecha de apertura</label>
    <type>Date</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Producto_de_Corredora_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_Corredora_Nectia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto de Corredora</label>
    <referenceTo>Producto_de_Corredora__c</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_del_Cliente1</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/Cons_RESTproductocontroller.cls
@RestResource(urlMapping='/producto/*')  //  https://bcoconsorcio--devbancorr.cs71.my.salesforce.com/services/apexrest/producto/crearproducto
global with sharing  class Cons_RESTproductocontroller {
    @HttpPost
    global static Cons_estructuraproducto_JSON.respuesta   crearproducto(Cons_estructuraproducto_JSON producto ) { 
        // Cons_estructuraproducto_JSON estprod=new Cons_estructuraproducto_JSON();
        Cons_estructuraproducto_JSON.respuesta estprodresp=new Cons_estructuraproducto_JSON.respuesta();
        list<AggregateResult> cantidad =[select count(rut__c) cantidad from account where rut__c=:producto.rut ];
        if(cantidad[0].get('cantidad')!=0){
            account ac=[select id from account where rut__c=:producto.rut];
            for(integer i=0;i<producto.productos.size();i++){
                system.debug('producto'+producto.productos);
                list<AggregateResult> existeproducto=[ select Count(Codigo_de_producto_corredora__c) total FROM Producto_de_Corredora__c 
                                                      where Codigo_de_producto_corredora__c=:decimal.valueOf(producto.productos.get(i).codigo) ];
                system.debug('existeproducto'+existeproducto);
                Producto_de_Corredora__c pro =new Producto_de_Corredora__c(); 
                if(existeproducto[0].get('total')==0){
                    
                    pro.Estado_Nectia__c=producto.productos.get(i).estado;
                    pro.Tipo_Nectia__c=producto.productos.get(i).tipo;
                    pro.Producto__c=producto.productos.get(i).producto;
                    pro.name=producto.productos.get(i).nombreproducto;//codigo de producto
                    pro.Codigo_de_producto_corredora__c=decimal.valueOf(producto.productos.get(i).codigo);
                    insert pro;
                }else{
                    pro =[select id  FROM Producto_de_Corredora__c where Codigo_de_producto_corredora__c=:decimal.valueOf(producto.productos.get(i).codigo) limit 1];                
                }
                system.debug('pro'+pro);
                list<AggregateResult> existeproductocliente=[ select Count(Id__c) total FROM Producto_del_Cliente__c 
                                                          where Id__c=:producto.productos.get(i).id];
                    system.debug('existeproductocliente'+existeproductocliente);
                    Producto_del_Cliente__c proc =new Producto_del_Cliente__c();
                    if(existeproductocliente[0].get('total')==0){
                proc.Cliente_Nectia__c=ac.id;
                proc.Producto_de_Corredora_Nectia__c=pro.id;
                proc.Id__c=producto.productos.get(i).id;
                proc.Estado_Nectia__c=producto.productos.get(i).estado;
                proc.Fecha_de_apertura_Nectia__c=date.valueOf(producto.productos.get(i).fecha);
                proc.RecordTypeId=[ SELECT Id, Name, SobjectType FROM RecordType where name=:'Producto cliente Corredora'].id;
                insert proc;
                estprodresp.mensage='producto guardado en salesforce';
                estprodresp.estado='guardado';
                estprodresp.codigo='0';
                    }else{
                      proc=[select id, Cliente_Nectia__c,Producto_de_Corredora_Nectia__c,Id__c,Estado_Nectia__c,Fecha_de_apertura_Nectia__c
                            FROM Producto_del_Cliente__c where Id__c=:producto.productos.get(i).id];  
                      proc.Cliente_Nectia__c=ac.id;
                      proc.Producto_de_Corredora_Nectia__c=pro.id;
                      proc.Id__c=producto.productos.get(i).id;
                      proc.Estado_Nectia__c=producto.productos.get(i).estado;
                      proc.Fecha_de_apertura_Nectia__c=date.valueOf(producto.productos.get(i).fecha);
                      proc.RecordTypeId=[ SELECT Id, Name, SobjectType FROM RecordType where name=:'Producto cliente Corredora'].id;
                      update proc;  
                     estprodresp.mensage='producto actualizado en salesforce';
                     estprodresp.estado='actualizado';
                     estprodresp.codigo='0';   
                    }
            }
            estprodresp.mensage='producto guardado en salesforce';
            estprodresp.estado='guardado';
            estprodresp.codigo='0';
        }else{
            estprodresp.mensage='rut no registrado en salesforce no se puede guardar producto';
            estprodresp.estado='denegado';
            estprodresp.codigo='1';   
        }
        producto.respuesta=estprodresp;
        
        return producto.respuesta;
    }
    
    public class respuesta {
        public String mensage;
        public String estado;
        public String codigo;
    }
}