CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/Consorcio_Org__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Se agrega validación por producto y acción.</description>
    <label>Consorcio Org</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/fields/Sales_project__c.field-meta.xml
<CustomField>
    <fullName>Sales_project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Todo perfil que se encuentre en está configuración se le gatillará funcionalidades exclusivas de SALES CLOUD PROJECT</description>
    <label>Sales project</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/fields/Validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Validation_rules__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Evitar validation rules</description>
    <label>Validation rules</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/cnf_sal_tri_account_Test.cls
@isTest
private class  cnf_sal_tri_account_Test {
    @testSetup static void dataload(){
        
        Map<String, SObject> mpsObjects = TestFactorySales.populateOrg();
        Id profileId = [SELECT Id FROM Profile WHERE Name =: Constants.PROFILE_EJECUTIVO_ATENCION_CLIENTE LIMIT 1].Id;
        List<User> lstUsr = [SELECT Id, Rut__c,profileId FROM User WHERE profileId =: profileId AND isActive = true LIMIT 1];
        Account acc = (Account)mpsObjects.get('Account');
        acc.OwnerId = lstUsr[0].Id;
        acc.PersonDoNotCall = false;
        acc.PersonHasOptedOutOfEmail = false;
        update acc;
    } 
    @isTest
    static void afterUpdateEmailTest(){
        Id profileId = [SELECT Id FROM Profile WHERE Name =: Constants.PROFILE_EJECUTIVO_ATENCION_CLIENTE LIMIT 1].Id;
        List<User> lstUsr = [SELECT Id, Rut__c,profileId FROM User WHERE profileId =: profileId AND isActive = true LIMIT 1];
        upsert new Consorcio_Org__c(SetupOwnerId=lstUsr[0].Id,Sales_project__c=true, Validation_rules__c = false);
        Account acc = [SELECT Id FROM Account WHERE RUT__C = '10854082-6'];
        
        system.runAs(lstUsr[0]){
            acc.PersonHasOptedOutOfEmail = true;
            test.startTest();
            update acc;
            test.stopTest();   
        }
        List<Case> lstCases2 = [SELECT Id, AccountId, Account.Name, CaseNumber FROM Case WHERE AccountId =: acc.Id];
        System.assertEquals(lstCases2[0].AccountId, acc.Id );
    }
    
    @isTest
    static void afterUpdateTelefonoTest(){
        Id profileId = [SELECT Id FROM Profile WHERE Name =: Constants.PROFILE_EJECUTIVO_ATENCION_CLIENTE LIMIT 1].Id;
        List<User> lstUsr = [SELECT Id, Rut__c,profileId FROM User WHERE profileId =: profileId AND isActive = true LIMIT 1];
        upsert new Consorcio_Org__c(SetupOwnerId=lstUsr[0].Id,Sales_project__c=true, Validation_rules__c = false);
        Account acc = [SELECT Id FROM Account WHERE RUT__C = '10854082-6'];
        system.runAs(lstUsr[0]){
            acc.PersonDoNotCall = true;
            test.startTest();
            update acc;
            test.stopTest();
        }
        List<Case> lstCases2 = [SELECT Id, AccountId, Account.Name, CaseNumber FROM Case WHERE AccountId =: acc.Id];
        System.assertEquals(lstCases2[0].AccountId, acc.Id );
    }
    
    @isTest
    static void afterUpdateTelefonoAndEmailTest(){
        Id profileId = [SELECT Id FROM Profile WHERE Name =: Constants.PROFILE_EJECUTIVO_ATENCION_CLIENTE LIMIT 1].Id;
        List<User> lstUsr = [SELECT Id, Rut__c,profileId FROM User WHERE profileId =: profileId AND isActive = true LIMIT 1];
        upsert new Consorcio_Org__c(SetupOwnerId=lstUsr[0].Id,Sales_project__c=true, Validation_rules__c = false);
        Account acc = [SELECT Id FROM Account WHERE RUT__C = '10854082-6'];
        system.runAs(lstUsr[0]){
            acc.PersonHasOptedOutOfEmail = true;
            acc.PersonDoNotCall = true;
            test.startTest();
            update acc;
            test.stopTest();
        }
        List<Case> lstCases2 = [SELECT Id, AccountId, Account.Name, CaseNumber FROM Case WHERE AccountId =: acc.Id];
        System.assertEquals(lstCases2[0].AccountId, acc.Id );
    }
}