CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/Consorcio_Org__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Se agrega validación por producto y acción.</description>
    <label>Consorcio Org</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/fields/Sincronizar_sales__c.field-meta.xml
<CustomField>
    <fullName>Sincronizar_sales__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Valida si el perfil puede sincronizar el presupuesto por producto.</description>
    <label>Sincronizar</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/QuoteTriggerHelper.cls
/**
 * @File Name          : QuoteTriggerHelper.cls
 * @Description        : 
 * @Author             : eayalcor@everis.com
 * @Group              : 
 * @Last Modified By   : eayalcor@everis.com
 * @Last Modified On   : 3/10/2020, 4:13:50 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/10/2020   eayalcor@everis.com     Initial Version
**/
public with sharing class QuoteTriggerHelper {

    /**
    * @description 
    * @author eayalcor@everis.com | 3/10/2020 
    * @param List<Quote> qtLst 
    * @param Map<Id Quote> oldMap 
    * @return void 
    **/
    public static void onBeforeUpdate(List<Quote> qtLst, Map<Id,Quote> oldMap){
        try{
            for (Quote quote : qtLst){
                if(quote.IsSyncing!= oldMap.get(quote.Id).IsSyncing){
                    if(!Consorcio_Org__c.getInstance(UserInfo.getProfileId()).Sincronizar_sales__c){
                        throw new UtilitiesSales.SalesException('Usuario no posee permisos para Sincronizar el presupuesto');           
                    }
                }
        	}
        }catch(Exception e){
            System.debug('Exception Message:' + e.getMessage());
            Trigger.new[0].addError(e.getMessage());
        }

    }
}