CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/Consorcio_Org__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Se agrega validación por producto y acción.</description>
    <label>Consorcio Org</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/fields/Participantes_Sales__c.field-meta.xml
<CustomField>
    <fullName>Participantes_Sales__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check para configurar que perfiles pueden trabajar en el objeto Participante_sales</description>
    <label>Participantes</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/participante_sales__c.object-meta.xml
<CustomObject>
    <label>Participante</label>
    <nameField>
        <label>Nombre Participante</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/Cliente_sales__c.field-meta.xml
<CustomField>
    <fullName>Cliente_sales__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>Participantes</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/correo_sales__c.field-meta.xml
<CustomField>
    <fullName>correo_sales__c</fullName>
    <description>Campo para almacenar el correo electrónico del participante de hipotecario.</description>
    <label>Correo</label>
    <type>Email</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/estado_participante_sales__c.field-meta.xml
<CustomField>
    <fullName>estado_participante_sales__c</fullName>
    <description>Campo para indicar si el participante aún forma parte o no del crédito hipotecario.</description>
    <label>Estado Participante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>No Vigente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/motivo_desactivacion_sales__c.field-meta.xml
<CustomField>
    <fullName>motivo_desactivacion_sales__c</fullName>
    <label>Motivo Desactivación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Decisión de cliente</fullName>
            </value>
            <value>
                <fullName>Rechazado por riesgo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/opportunity_participante_sales__c.field-meta.xml
<CustomField>
    <fullName>opportunity_participante_sales__c</fullName>
    <description>Campo que relaciona el objeto Participante con el objeto Oportunidad.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Participantes</relationshipLabel>
    <relationshipName>participantes_sales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/remuneracion_sales__c.field-meta.xml
<CustomField>
    <fullName>remuneracion_sales__c</fullName>
    <label>Remuneración</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/rol_participante_sales__c.field-meta.xml
<CustomField>
    <fullName>rol_participante_sales__c</fullName>
    <description>Campo para almacenar el rol del participante en el crédito hipotecario.</description>
    <label>Rol Participante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Co Deudor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/rut_sales__c.field-meta.xml
<CustomField>
    <fullName>rut_sales__c</fullName>
    <description>Campo para almacenar el rut del participante de hipotecario.</description>
    <label>Rut</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/telefono_fijo_sales__c.field-meta.xml
<CustomField>
    <fullName>telefono_fijo_sales__c</fullName>
    <description>Campo para almacenar el número de red fija del participante.</description>
    <label>Teléfono Fijo</label>
    <type>Phone</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/participante_sales__c/fields/telefono_movil_sales__c.field-meta.xml
<CustomField>
    <fullName>telefono_movil_sales__c</fullName>
    <description>Campo para almacenar el número móvil del participante de hipotecario.</description>
    <label>Teléfono Móvil</label>
    <type>Phone</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/ActivateParticipantController.cls
/**
 * @File Name          : ActivateParticipantController.cls
 * @Description        : 
 * @Author             : zsuanaza@everis.com
 * @Group              : 
 * @Last Modified By   : zsuanaza@everis.com
 * @Last Modified On   : 23-01-2020
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    1/23/2020         zsuanaza@everis.com    Initial Version
**/
public without sharing class ActivateParticipantController {
	    /**
    * @description 
    * @author eayalcor@everis.com | 1/20/2020 
    * @param Id oppId 
    * @return Map<String, List<String>> 
    **/
    @AuraEnabled
    public static responseParticipant getInitialData(Id participantId){
        system.debug('ID-->'+participantId);
        responseParticipant res = new responseParticipant();
        List<participante_sales__c> partList = [SELECT Id, Name, Cliente_sales__c, correo_sales__c, 
                                           telefono_movil_sales__c, telefono_fijo_sales__c, 
                                           rol_participante_sales__c, rut_sales__c, estado_participante_sales__c, 
                                           remuneracion_sales__c, opportunity_participante_sales__c,
                                           opportunity_participante_sales__r.Stagename,motivo_desactivacion_sales__c
                                           FROM participante_sales__c 
                                           WHERE id=:participantId];
		system.debug('PART --->'+partList);
        res.Motivos = UtilitiesSales.getPicklistData(participante_sales__c.motivo_desactivacion_sales__c);
        system.debug('res.Motivos--->'+res.Motivos);
        if((partList != null || !partList.isEmpty())&&
           (partList[0].opportunity_participante_sales__r.Stagename == CONSTANTS.OPPORTUNITY_STAGE_CONTACTO)){
			res.Participant = partList[0];  
        }else{
            res.Participant = null;
        }
        system.debug('res--->'+res);
        return res;
    }
    @AuraEnabled
    public static String activateOppParticipant(Id participantId){ 
        try{
            system.debug('Profile----->'+Consorcio_Org__c.getInstance(UserInfo.getProfileId()));
            if(Consorcio_Org__c.getInstance(UserInfo.getProfileId()).Participantes_Sales__c){
                participante_sales__c part = new participante_sales__c();
                part.id = participantId;
                part.estado_participante_sales__c = CONSTANTS.PARTICIPANT_ESTADO_VIGENTE;
                part.motivo_desactivacion_sales__c = '';
                update part;
                System.debug('PARTICIPANTE--<'+ part);
                return 'OK'; 
            }else{
                return 'ERROR: Su perfil no puede realizar la acción solicitada.';
            }
        }catch(exception e){
            return 'ERROR: Contactar a su administrador';
        }   
    }
    @AuraEnabled
    public static String deactivateOppParticipant(Id participantId,string motivo){ 
        try{
            if(Consorcio_Org__c.getInstance(UserInfo.getProfileId()).Participantes_Sales__c){
                participante_sales__c part = new participante_sales__c();
                part.id = participantId;
                part.estado_participante_sales__c = CONSTANTS.PARTICIPANT_ESTADO_NO_VIGENTE;
                part.motivo_desactivacion_sales__c = motivo;
                update part;
                System.debug('PARTICIPANTE--<'+ part);
                return 'OK';   
            }else{
                return 'ERROR: Su perfil no puede realizar la acción solicitada.';
            }
        }catch(exception e){
            return 'ERROR: Contactar a su administrador';
        }   
    }
    public class responseParticipant{
        @AuraEnabled public List<String> Motivos;
        @AuraEnabled public participante_sales__c Participant;
    }
}