CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/Consorcio_Org__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Se agrega validación por producto y acción.</description>
    <label>Consorcio Org</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/fields/Sales_project__c.field-meta.xml
<CustomField>
    <fullName>Sales_project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Todo perfil que se encuentre en está configuración se le gatillará funcionalidades exclusivas de SALES CLOUD PROJECT</description>
    <label>Sales project</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/classes/ProposalController_Test.cls
@isTest
public class ProposalController_Test {
    
        
	@isTest 
    static void proposalControllerQuoteTest(){
        Test.startTest();
        Map<String,SObject> mpsObjects = TestFactorySales.populateOrg();       
        Account acc = (Account)mpsObjects.get('Account');
        Id idProd2 = Test.getStandardPricebookId(); 
        User user = (User)mpsObjects.get('User');
        Map<String,SObject> mpsOppObjects = TestFactorySales.createOpportunityWithProduct(idProd2,acc.Id,user.Id);
        Quote qte = (Quote)mpsOppObjects.get('Quote');
        qte.Numero_de_Propuesta_sales__c = '0';
        qte.Numero_de_Cotizacion_sales__c = '1234';
        update qte;
        
        
        upsert new Consorcio_Org__c(SetupOwnerId=user.profileId, Sales_project__c = FALSE);
        
        System.runAs(user){
            
            ProposalController.StoreProposalClass stPro = new ProposalController.StoreProposalClass();
            stPro.estado = 0;
            stPro.mensaje = 'Propuesta ingresada correctamente';

            String json = JSON.serialize(stPro);
            SalesCalloutMock fakeResponse = new SalesCalloutMock(200,
                                                     'OK',
                                                     '{ "estado": 0, "mensaje": "Propuesta ingresada correctamente" }',
                                                     null);
            Test.setMock(HttpCalloutMock.class, fakeResponse);
            ProposalController.StoreProposalClass sp = ProposalController.getStoreProposal(qte.Id);
            System.assertEquals(-1, sp.estado);
        }
        
        Test.stopTest();
    }
    
    @isTest 
    static void proposalControllerQuoteTest2(){
                    
        Test.startTest();
        
        Map<String,SObject> mpsObjects = TestFactorySales.populateOrg();       
        Account acc = (Account)mpsObjects.get('Account');
        Id idProd2 = Test.getStandardPricebookId(); 
        User user = (User)mpsObjects.get('User');
        Map<String,SObject> mpsOppObjects = TestFactorySales.createOpportunityWithProduct(idProd2,acc.Id,user.Id);
        Quote qte = (Quote)mpsOppObjects.get('Quote');
        qte.Numero_de_Propuesta_sales__c = '1';
        qte.Numero_de_Cotizacion_sales__c='1';
        update qte;
        
        
        System.runAs(user){

            ProposalController.StoreProposalClass stPro = new ProposalController.StoreProposalClass();
            stPro.estado = 0;
            stPro.mensaje = 'Propuesta ingresada correctamente';

            String json = JSON.serialize(stPro);
            SalesCalloutMock fakeResponse = new SalesCalloutMock(200,
                                                     'OK',
                                                     '{ "estado": 0, "mensaje": "Propuesta ingresada correctamente" }',
                                                     null);
            Test.setMock(HttpCalloutMock.class, fakeResponse);
            ProposalController.StoreProposalClass sp = ProposalController.getStoreProposal(qte.Id);
            Boolean isStageOK = ProposalController.getOppStage(qte.id);
            //System.assertEquals(true, isStageOk);
            System.assertEquals(-1, sp.estado);
        }
                    
        Test.stopTest();
    }

}