CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/Consorcio_Org__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Se agrega validación por producto y acción.</description>
    <label>Consorcio Org</label>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/fields/Sales_project__c.field-meta.xml
<CustomField>
    <fullName>Sales_project__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Todo perfil que se encuentre en está configuración se le gatillará funcionalidades exclusivas de SALES CLOUD PROJECT</description>
    <label>Sales project</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Consorcio_Org__c/fields/Validation_rules__c.field-meta.xml
<CustomField>
    <fullName>Validation_rules__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Evitar validation rules</description>
    <label>Validation rules</label>
    <type>Checkbox</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/Producto_de_Seguros__c.object-meta.xml
<CustomObject>
    <label>Producto de Seguro</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos de Seguro</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/Codigo_de_Producto_nectia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Producto_nectia__c</fullName>
    <externalId>true</externalId>
    <label>Codigo Operacional</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/Estado_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Nectia__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_de_Seguros__c/fields/L_nea__c.field-meta.xml
<CustomField>
    <fullName>L_nea__c</fullName>
    <label>Línea</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colectivos</fullName>
            </value>
            <value>
                <fullName>FFMM</fullName>
            </value>
            <value>
                <fullName>Generales</fullName>
            </value>
            <value>
                <fullName>Rentas Vitalicias</fullName>
            </value>
            <value>
                <fullName>Vida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/Producto_del_Cliente__c.object-meta.xml
<CustomObject>
    <label>Producto del Cliente</label>
    <nameField>
        <label>Producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos del Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Cliente_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Cliente_Nectia__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_de_cliente</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Estado_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Estado_Nectia__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVA</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>CASTIGO</fullName>
            </value>
            <value>
                <fullName>FORWARD INGRESO</fullName>
            </value>
            <value>
                <fullName>FORWARD MODIFICADO</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>INGRESO</fullName>
            </value>
            <value>
                <fullName>MODIFICADO</fullName>
            </value>
            <value>
                <fullName>No Vigente</fullName>
            </value>
            <value>
                <fullName>VENCIDO</fullName>
            </value>
            <value>
                <fullName>VIGENTE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/L_nea__c.field-meta.xml
<CustomField>
    <fullName>L_nea__c</fullName>
    <formula>TEXT(Producto_de_Seguros_Nectia__r.L_nea__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Línea</label>
    <type>Text</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Producto_de_Seguros_Nectia__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_Seguros_Nectia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto de Seguros</label>
    <referenceTo>Producto_de_Seguros__c</referenceTo>
    <relationshipLabel>Productos del Cliente</relationshipLabel>
    <relationshipName>Productos_del_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/fields/Productos_asociados__c.field-meta.xml
<CustomField>
    <fullName>Productos_asociados__c</fullName>
    <label>Productos asociados</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acciones</fullName>
            </value>
            <value>
                <fullName>Fondos Mutuos</fullName>
            </value>
            <value>
                <fullName>Depósitos a Plazo</fullName>
            </value>
            <value>
                <fullName>ETF</fullName>
            </value>
            <value>
                <fullName>Fondos de Inversión</fullName>
            </value>
            <value>
                <fullName>Renta Fija</fullName>
            </value>
            <value>
                <fullName>Simultáneas</fullName>
            </value>
            <value>
                <fullName>Sitio News</fullName>
            </value>
            <value>
                <fullName>Profundidad de Mercado</fullName>
            </value>
            <value>
                <fullName>Alarmas</fullName>
            </value>
            <value>
                <fullName>Analisis Técnico</fullName>
            </value>
            <value>
                <fullName>Información de Mercado</fullName>
            </value>
            <value>
                <fullName>Servicio Emaling</fullName>
            </value>
            <value>
                <fullName>Pactos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/recordTypes/Producto_cliente_Banco.recordType-meta.xml
<RecordType>
    <fullName>Producto_cliente_Banco</fullName>
    <active>true</active>
    <label>Producto cliente Banco</label>
</RecordType>

CNSDEVCOLECT/force-app/main/default/objects/Producto_del_Cliente__c/recordTypes/Producto_cliente_Seguros.recordType-meta.xml
<RecordType>
    <fullName>Producto_cliente_Seguros</fullName>
    <active>true</active>
    <label>Producto cliente Seguros</label>
</RecordType>

CNSDEVCOLECT/force-app/main/default/classes/ProductoDelClienteTriggerTest.cls
/*********************************************************************************************************
@Author       curbinav@everis.com
@name         ProductoDelClienteTriggerTest
@CreateDate   11/11/2019
@Description  Test class for ProductoDelClienteTriggerHelper
***********************************************************************************************************
History of changes: 
-----------------------------------------------------------------------------------------------------------
Date          Developer                     Comments   
-----------------------------------------------------------------------------------------------------------
11/11/2019    curbinav@everis.com           W-000073 - (Vista 360° Cliente) - Ingreso Sección Cliente (Resumen)
**********************************************************************************************************/
@isTest
public class ProductoDelClienteTriggerTest {
    
    private static final Map<String, SObject> mapsObjects = TestFactorySales.populateOrg();
	
    /**
     * Flag multiproducto false
     * 
     **/
    @isTest static void TestFlagMultiprodcutoFalse() {

        User usr=(User) mapsObjects.get('User2');
        upsert new Consorcio_Org__c(SetupOwnerId=Usr.Id,Sales_project__c=true, Validation_rules__c = false);
        
        System.runAs(usr) {
            // Perform test
            Test.startTest();
    
            // Crear nueva cuenta persona
            Account personAccount = new Account();
            personAccount.RUT__c = '2-7';
            personAccount.LastName = 'Lastname';
            personAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
            
            insert personAccount;
            System.debug('personAccount: ' + personAccount);
            
            Producto_Del_Cliente__c pdc1 = new Producto_Del_Cliente__c();
            pdc1.RecordTypeId = Schema.SObjectType.Producto_Del_Cliente__c.getRecordTypeInfosByDeveloperName().get('Producto_cliente_Seguros').getRecordTypeId();
			pdc1.Cliente_Nectia__c = personAccount.Id;
            
            insert pdc1;
            System.debug('Inserted pdc1 ' + pdc1);
            
            Account personAccountDB = [SELECT Id, Multiproducto_sales__c                                       
										FROM Account 
                                       	WHERE Id = :personAccount.Id LIMIT 1];
            System.debug('personAccountDB: ' + personAccountDB);
            System.assertEquals(false, personAccountDB.Multiproducto_sales__c, 'Se espera que no sea multiproducto');
            
            Test.stopTest();
        }
    }

    /**
     * Flag multiproducto true
     * 
     **/
    @isTest static void TestFlagMultiprodcutoTrue() {

        User usr=(User) mapsObjects.get('User2');
        upsert new Consorcio_Org__c(SetupOwnerId=Usr.Id,Sales_project__c=true, Validation_rules__c = false);
        
        System.runAs(usr) {
            // Perform test
            Test.startTest();
    
            // Crear nueva cuenta persona
            Account personAccount = new Account();
            personAccount.RUT__c = '2-7';
            personAccount.LastName = 'Lastname';
            personAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
            
            insert personAccount;
            System.debug('personAccount: ' + personAccount);
            
            Producto_Del_Cliente__c pdc1 = new Producto_Del_Cliente__c();
            pdc1.RecordTypeId = Schema.SObjectType.Producto_Del_Cliente__c.getRecordTypeInfosByDeveloperName().get('Producto_cliente_Seguros').getRecordTypeId();
			pdc1.Cliente_Nectia__c = personAccount.Id;
                        
            Producto_Del_Cliente__c pdc2 = new Producto_Del_Cliente__c(); 
            pdc2.RecordTypeId = Schema.SObjectType.Producto_Del_Cliente__c.getRecordTypeInfosByDeveloperName().get('Producto_cliente_Banco').getRecordTypeId();
			pdc2.Cliente_Nectia__c = personAccount.Id;
            pdc2.Name = 'APV';
            pdc2.Productos_asociados__c = 'Acciones';
            pdc2.Estado_Nectia__c = 'VIGENTE';
            
            Producto_de_Seguros__c pds = new Producto_de_Seguros__c();
            pds.L_nea__c = 'FFMM';
            pds.Codigo_de_Producto_nectia__c = '9999';
            insert pds;
            
            pdc2.Producto_de_Seguros_Nectia__c = pds.Id;
            
            List<Producto_Del_Cliente__c> pdcList = new List<Producto_Del_Cliente__c>();
            pdcList.add(pdc1);
            pdcList.add(pdc2);
            insert pdcList;
            System.debug('Inserted list pdc2: ' + pdcList);
            
            Account personAccountDB2 = [SELECT Id, Multiproducto_sales__c                                       
										FROM Account 
                                       	WHERE Id = :personAccount.Id LIMIT 1];
            //System.debug('personAccountDB2: ' + personAccountDB2);
            //System.assertEquals(true, personAccountDB2.Multiproducto_sales__c, 'Se espera que sea multiproducto');

            delete pdcList.get(0);

            Account personAccountDB = [SELECT Id, Multiproducto_sales__c                                       
										FROM Account 
                                       	WHERE Id = :personAccount.Id LIMIT 1];
            //System.debug('personAccountDB: ' + personAccountDB);
            System.assertEquals(false, personAccountDB.Multiproducto_sales__c, 'Se espera que no sea multiproducto');
            
            Test.stopTest();
        }
    }

}